### ISSUE TITLE
Can't update sources

### ISSUE THREAD

**Issue by agucova** [StevenBlack/hosts#39] opened 2015-11-10 10:59 UTC
While updating sources I get:
>Updating source /Users/ForgottenPlayer/Downloads/hosts-master 2/data/adaway.org from http://adaway.org/hosts.txt
> Problem getting file:  http://adaway.org/hosts.txt
> Traceback (most recent call last):
  > File "updateHostsFile.py", line 384, in <module>
     main()
  > File "updateHostsFile.py", line 93, in main
     promptForUpdate()
  > File "updateHostsFile.py", line 107, in promptForUpdate
     updateAllSources()
  > File "updateHostsFile.py", line 176, in updateAllSources
     updatedFile = updatedFile.replace('\r', '') #get rid of carriage-return symbols
> AttributeError: 'NoneType' object has no attribute 'replace'

Any ideas?

**Comment by agucova** [comment] 2015-11-10 11:01
Problem solved, it was privoxy blocking the website, sorry!

**Comment by StevenBlack** [comment] 2015-11-10 13:59
Thanks @agucova — I think the script should handle data update errors and continue using the old source, as opposed to crash.

Adding label "enhancement".

**Comment by FadeMind** [comment] 2015-11-10 14:34
@StevenBlack  Related: https://github.com/StevenBlack/hosts/issues/26

**Comment by StevenBlack** [comment] 2015-11-10 14:48
@FadeMind yup!  Thanks.

Closing, duplicate of #26.

**Closed by StevenBlack** 2015-11-10 14:48 UTC
Labels: enhancement
