### ISSUE TITLE
Add `! Title:` to the filter lists so that they can show pretty names when added to e.g. uBlock

### ISSUE THREAD

**Issue by FatOrangutan** [StevenBlack/hosts#744] opened 2018-08-05 18:14 UTC
STR: add `https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts` as a custom filter to uBlock Origin

AR: It shows the full url instead of saying `Unified hosts`:

![capture](https://user-images.githubusercontent.com/8336638/43688602-7909e6fa-9909-11e8-8a63-dbe2dcfad9e4.PNG)

Relevant: https://github.com/gorhill/uBlock/issues/2501

**Comment by StevenBlack** [comment] 2018-08-05 18:46
This would be a prepend in [`write_opening_header()`](https://github.com/StevenBlack/hosts/blob/master/updateHostsFile.py#L902-L970).

It would be good to  `.join(header_params["extensions"])` into the title.

**Comment by funilrys** [comment] 2018-09-01 08:09
Hi @FatOrangutan I'm not deep into that but I can write the patch into the [`python3only`](https://github.com/StevenBlack/hosts/tree/python3only) branch.

My question is which of the following is okay for you ?

```
# ! Title: StevenBlack/hosts
0.0.0.0 github.com
0.0.0.0 git.io
```

```
! Title: StevenBlack/hosts
0.0.0.0 github.com
0.0.0.0 git.io
```

I'm asking because your referenced issue is talking about the filter list. But this repository only produce the hosts file or am I missing something else in between ?

Have a nice day/night.

**Comment by lightswitch05** [comment] 2018-09-01 12:35
I wouldn't mind adding this feature directly into my list if that's would be useful

**Comment by FatOrangutan** [comment] 2018-09-01 20:40
Hi @funilrys, `! Title: StevenBlack/hosts` is the one that uBlock (and I think other adblockers) can recognise.

>I'm asking because your referenced issue is talking about the filter list. But this repository only produce the hosts file

That's a good point that I hadn't considered. Given this, I would expect my issue to be out of scope, but then StevenBlack seemed to be interested so I don't know..

**Comment by funilrys** [comment] 2018-09-04 17:34
Hi @FatOrangutan,
Daniel @lightswitch05,
Steve @StevenBlack,

# To answer @lightswitch05
You can if you want (and you don't have to ask) but my understanding make this impossible to me if you manage hosts file.

# For the context

I do not use or generate filter list (yet !? :thinking: ) so I'm not familiar with the expected behavior.
So I asked @FatOrangutan if the expected line should be in a hosts file comment like :

```
# ! Title: StevenBlack/hosts (Note the presence of # at the beginning)
```

or  a filter comment (is that actually a comment ? :thinking: ) like :

```
! Title: StevenBlack/hosts (Note the non-presence of # at the beginning)
```

# From @FatOrangutan's answer to @StevenBlack and other(s)

If the expected line (we may need someone else to confirm that point) should be like:

```
! Title: StevenBlack/hosts (Note the non-presence of # at the beginning)
```

Then this issue is out of scope as it does not respect the hosts file format.

But if someone can confirm that 

```
# ! Title: StevenBlack/hosts (Note the presence of # at the beginning)
```

Also works for as expected, then this issue is not out of scope and I'm ready to write the code (or someone else if I take my time :joy_cat: )!

# Conclusion

We need someone another 4 eyes who live with filter list (also known as adblock filter list isn't that right or I'm lost again ? :thinking: ) to confirm the scope of this issue.

Have a nice day/night.

**Comment by FatOrangutan** [comment] 2018-09-04 19:40
I tested this in my filter lists, and `# Title: ` works too. `# ! Title: ` doesn't work though. Would be great if somebody else could confirm.

**Comment by gorhill** [comment] 2018-09-08 23:28
I confirm that uBO will accept `# Title: `.

**Closed** 2018-10-11 18:06 UTC
Labels: enhancement

**Comment by funilrys** [comment] 2019-07-13 10:34
Let's reopen this and close #843 Steve @StevenBlack ... Will write the code when I have a bit of time today or tomorrow.
