### ISSUE TITLE
dnsmasq

### ISSUE THREAD

**Issue by imbicile** [StevenBlack/hosts#989] opened 2019-05-31 07:52 UTC
**dnsmasq cfg**
```
......................
addn-hosts=/etc/dnsmasq.hosts/banner_add_hosts_1
addn-hosts=/etc/dnsmasq.hosts/banner_add_hosts_2
......................
```
**LOG**
`bad address at /etc/dnsmasq.hosts/banner_add_hosts_1 line 8`

**FIX**
`# fe80::1%lo0 localhost`

**i use raw file bash script**
`wget -O /etc/dnsmasq.hosts/banner_add_hosts_1 http://sbc.io/hosts/alternates/fakenews-gambling-porn/hosts`

**Comment by dnmTX** [comment] 2019-06-02 03:17
Steve @StevenBlack  they keep popping up like 🍄 🍄 🍄  after the 🌧 
😉

**Comment by StevenBlack** [comment] 2019-06-03 00:48
Hi @imbicile, thank you for this input.

This is a duplicate of #333, which is closed – won't fix.

Closing.

**Closed by StevenBlack** 2019-06-03 00:48 UTC

**Comment by kurahaupo** [comment] 2022-11-29 03:35
@StevenBlack 

I'm using Linux on hosts with multiple adaptors connected to multiple networks, and in that context having interface tags on IPv6 link-local addresses is important. Commenting them out is not an option for me.

Using interface tags in `/etc/hosts` isn't some weird thing that only MacOS needs: any IPv6 enabled host can wind up needing them, but what's different about MacOS is that it can consult `/etc/hosts` to identify a default router, so they're a lot more common there.

As noted by [RIPE Labs](https://labs.ripe.net/author/philip_homburg/whats-the-deal-with-ipv6-link-local-addresses/), specifying a source interface is necessary when making an outbound connection to a link-local address, and [RFC 4007](http://www.rfc-editor.org/info/rfc4007) specifies that attaching <tt>%<i>zone-id</i></tt> tags to IPv6 addresses is the appropriate way of doing so. ("Zone" in this context means the network segment to which an interface is connected, so the usual way to identify zones is by the name or number of the respective interface.)

This means that tagged IPv6 addresses should be accepted in all contexts where the address can be used used to initiate connections; this includes entries in `/etc/hosts`.

Network tooling applications like `ping` or `nmap` have a `-I` flag or equivalent to specify the source interface or address, but most ordinary applications do not have a way of specifying the source interface, so it can only be controlled by including it as part of the address, and that in turn can only be put in `/etc/hosts`.

Please reconsider fixing this bug.

**Comment by StevenBlack** [comment] 2022-11-29 16:21
Hi Martin @kurahaupo thank you for this.

You know, appending to an issue closed 40-months ago isn't a great way to draw attention to something.

If you feel this is a bug can you please open a new issue, possibly referencing this 3 1/2 year old conversation, and clearly explain how this is a bug, and exactly what you recommend we do to fix this.

Also note that pull requests speak more loudly, and carry more weight, than an issue ever can.
