### ISSUE TITLE
Add title to fakenews extension?

### ISSUE THREAD

**Issue by Jezza-x3** [StevenBlack/hosts#843] opened 2018-11-26 01:57 UTC
Can you add '# Title: Fake News hosts' on line one? It makes it show up with the name rather than the URL for ublock origin.

**Comment by StevenBlack** [comment] 2018-11-26 03:40
This is a duplicate of Issue #744, which is closed (?!).

**Comment by Ultrabenosaurus** [comment] 2019-07-13 10:07
Sorry to resurrect this but the issue is still present as far as I can tell. I'm not sure why #744 was closed, looking at the comments and the fact no PR tagged that issue it seems that while a solution was identified it was never implemented? 

I have added the Unified + Fakenews list to both uBlock Origin and AdGuard Home and neither show a title. The title column is blank on AdGuard Home while uBO shows the URL. Opening the list directly from both the GitHub and non-GitHub links shows that neither include any sort of title declaration, that I can see.

**Comment by funilrys** [comment] 2019-07-13 10:41
I don't bother to write a PR if an issue is flagged as closed @Ultrabenosaurus by OP or even Steve... 

Steve @StevenBlack, let's follow up at https://github.com/StevenBlack/hosts/issues/744 because it has more details in the way we/I can implement this.

Cheers,
Nissar

**Comment by Ultrabenosaurus** [comment] 2019-07-13 11:22
@funilrys sorry for any confusion, I didn't mean to say "the issue is closed so why did no one do a PR?" but more "a solution was confirmed but no PR was created, so why is it closed?". I think it is reasonable to assume a closed issue does not need coding or a PR, but it seemed odd to me that #744 was closed despite the solution not being implemented.

**Comment by funilrys** [comment] 2019-07-13 12:02
Maybe OP did not understand how GitHub works ... People want everything instantly but forget that we aren't necessarily paid for what we do out here and that we mostly do what do out here in our side/free time...

Anyway @Ultrabenosaurus PR #1014  in pending. It's up to Steve @StevenBlack now :smile_cat:.

Have a good afternoon.

Cheers,
Nissar

**Comment by funilrys** [comment] 2019-07-15 21:22
This one can now be closed as #1014 was merged. @StevenBlack @Ultrabenosaurus

**Comment by StevenBlack** [comment] 2019-07-15 21:24
Closing.  Thanks everybody!

**Closed by StevenBlack** 2019-07-15 21:24 UTC
