### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 16380: character maps to <undefined>

### ISSUE THREAD

**Issue by tormit** [StevenBlack/hosts#613] opened 2018-05-14 20:06 UTC
Suddenly I'm getting this error when trying to update my host list by running custom profile:

`python updateHostsFile.py --auto --backup --extensions porn gambling fakenews`

Full output:
```
Updating source data\adaway.org from https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt
Updating source data\add.2o7Net from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
Updating source data\add.Dead from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Dead/hosts
Updating source data\add.Risk from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
Updating source data\add.Spam from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
Updating source data\Badd-Boyz-Hosts from https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts
Updating source data\CoinBlockerList from https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts_browser
Updating source data\KADhosts from https://raw.githubusercontent.com/azet12/KADhosts/master/KADhosts.txt
Updating source data\malwaredomainlist.com from http://www.malwaredomainlist.com/hostslist/hosts.txt
Updating source data\mvps.org from http://winhelp2002.mvps.org/hosts.txt
Updating source data\someonewhocares.org from http://someonewhocares.org/hosts/zero/hosts
Updating source data\StevenBlack from https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts
Updating source data\UncheckyAds from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
Updating source data\yoyo.org from https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext&useip=0.0.0.0
Updating source extensions\fakenews from https://raw.githubusercontent.com/marktron/fakenews/master/fakenews
Updating source extensions\gambling from https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/gambling-hosts
Updating source extensions\porn\clefspeare13 from https://raw.githubusercontent.com/Clefspeare13/pornhosts/master/0.0.0.0/hosts
Updating source extensions\porn\sinfonietta from https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/pornography-hosts
Updating source extensions\porn\sinfonietta-snuff from https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/snuff-hosts
Updating source extensions\social from https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/social-hosts
Traceback (most recent call last):
  File "updateHostsFile.py", line 1500, in <module>
    main()
  File "updateHostsFile.py", line 187, in main
    merge_file = create_initial_file()
  File "updateHostsFile.py", line 636, in create_initial_file
    write_data(merge_file, curFile.read())
  File "C:\Program Files (x86)\Python36-32\lib\encodings\cp1257.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 16380: character maps to <undefined>
```

It was working fine few weeks ago. Updated the program to the latest version, but still this error.

**Comment by StevenBlack** [comment] 2018-05-15 00:11
Hi Tromi @tormit, what's your `python --version`?

Try it under `python3`?

**Comment by funilrys** [comment] 2018-05-15 11:30
Hi Steven @StevenBlack his log suggests that he is under windows + python 3.6.x :

> `C:\Program Files (x86)\Python36-32\lib\encodings\cp1257.py `

But Tromi @tormit are you using the latest update script? Cause #520 and its children were supposed to fix every `Unicode*Error` :thinking:

**Comment by tormit** [comment] 2018-05-15 17:34
Yes, it's Python 3.6.5 and I have the latest version of this software.
I discovered that _data/StevenBlack_ is causing the problem. Deleted this folder and it generated hosts file successfully.

**Comment by funilrys** [comment] 2018-05-16 06:48
This time Steven @StevenBlack  it is because we do not touch/convert to idna commented lines ...

The issue is the following 

```
# Office Telemetry Upload Reporting – ‘Heartbeart’ and error events that 
                                   ---^
```

**Comment by luipugs** [comment] 2018-06-19 01:38
Happening in current HEAD (2246df0c0b0b80c6743d395f8d3c928d29457972)
```
$ python updateHostsFile.py
Do you want to update all data sources? [Y/n] y
Updating source ./data/adaway.org from https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt
Updating source ./data/add.2o7Net from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
Updating source ./data/add.Dead from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Dead/hosts
Updating source ./data/add.Risk from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
Updating source ./data/add.Spam from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
Updating source ./data/Badd-Boyz-Hosts from https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts
Updating source ./data/CoinBlockerList from https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
Updating source ./data/KADhosts from https://raw.githubusercontent.com/azet12/KADhosts/master/KADhosts.txt
Updating source ./data/lightswitch05 from https://raw.githubusercontent.com/lightswitch05/hosts/master/ads-and-tracking-extended.txt
Updating source ./data/malwaredomainlist.com from http://www.malwaredomainlist.com/hostslist/hosts.txt
Updating source ./data/mvps.org from http://winhelp2002.mvps.org/hosts.txt
Updating source ./data/someonewhocares.org from http://someonewhocares.org/hosts/zero/hosts
Updating source ./data/StevenBlack from https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts
Updating source ./data/UncheckyAds from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
Updating source ./data/yoyo.org from https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext&useip=0.0.0.0
Updating source ./extensions/fakenews from https://raw.githubusercontent.com/marktron/fakenews/master/fakenews
Updating source ./extensions/gambling from https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/gambling-hosts
Updating source ./extensions/porn/clefspeare13 from https://raw.githubusercontent.com/Clefspeare13/pornhosts/master/0.0.0.0/hosts
Updating source ./extensions/porn/sinfonietta from https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/pornography-hosts
Updating source ./extensions/porn/sinfonietta-snuff from https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/snuff-hosts
Updating source ./extensions/social from https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/social-hosts
Do you want to exclude any domains?
For example, hulu.com video streaming must be able to access its tracking and ad servers in order to play video. [Y/n] n
OK, we'll only exclude domains in the whitelist.
Traceback (most recent call last):
  File "updateHostsFile.py", line 1513, in <module>
    main()
  File "updateHostsFile.py", line 187, in main
    merge_file = create_initial_file()
  File "updateHostsFile.py", line 640, in create_initial_file
    write_data(merge_file, start + curFile.read() + end)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 394551: ordinal not in range(128)
```

Using Python 2.

**Comment by funilrys** [comment] 2018-07-03 20:59
That one is related to #700 @luipugs not this issue.

**Comment by gfyoung** [comment] 2018-09-07 03:59
@StevenBlack : Judging from the conversation, I think this one can be closed?

**Comment by StevenBlack** [comment] 2018-09-07 05:12
@gfyoung yup!

Closing.

**Closed by StevenBlack** 2018-09-07 05:12 UTC
