### ISSUE TITLE
MSN.com - Blocked elements

### ISSUE THREAD

**Issue by THEtomaso** [StevenBlack/hosts#539] opened 2018-03-15 20:50 UTC
### List the website(s) you're having issues:
`MSN.com`

### Example:
`https://www.msn.com/nb-no/underholdning/`

### What happens?:
Some elements are blocked

### Screenshot:
![msn](https://user-images.githubusercontent.com/9382674/37489978-3fc994be-2891-11e8-9bbc-c155528988f1.jpg)

### Problem filter:
Dan Pollock's hosts file

### Problem rule:
`m.adnxs.com`

### Possible fix:
`@@m.adnxs.com$domain=msn.com`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.8.1 (x64)
- Adblock Extension/version: uBlock Origin v1.15.10

**Comment by StevenBlack** [comment] 2018-03-15 22:03
Thanks @THEtomaso, that's a perfect issue report, right there.

**Comment by StevenBlack** [comment] 2018-03-15 22:23
@tyzbit I can't get to msn.com at all.

For me personally, that's not a problem, I could live with that   😈  but for some folks...

From my location (Central Canada) it wants to carom off `a-0003.a-msedge.net` which is in [`data/tyzbit/hosts`](https://github.com/StevenBlack/hosts/blob/master/data/tyzbit/hosts).

I'm going to revert back to the old source, and regen.

Sorry @THEtomaso, stand by.

**Comment by dnmTX** [comment] 2018-03-15 22:28
@StevenBlack  i just tried to reproduce it and everything looks good on my end.Looks like this is a uBlock specific rule and nothing to do with your lists.I can also open msn.com with no problems.
![msn underholdning - kjendis tv-guide sladder film tv video](https://user-images.githubusercontent.com/34774426/37494307-4025c826-2876-11e8-8470-657b7d9afe97.png)

**Comment by StevenBlack** [comment] 2018-03-15 22:37
@dnmTX it's mos def the hosts file.  I have unable to load on multiple machines, multiple browsers on each.

**Comment by StevenBlack** [comment] 2018-03-15 22:42
@THEtomaso fixed in [Release 1..32](https://github.com/StevenBlack/hosts/releases/tag/v1.3.2), on master branch now.  Sorry for the hassle.

**Comment by dnmTX** [comment] 2018-03-15 22:45
@StevenBlack  well if you planing to revert back to the old @tyzbit's list i'd say don't(i thing we all agreed that need it improvements and the way it was it's useless).This way i can load the new list as a addition to yours without worrying about duplicates.You can also link the new @tyzbit's list in your repo for whoever want's it .

**Comment by THEtomaso** [comment] 2018-03-15 22:52
> everything looks good on my end

The MSN site changes continously.
At the moment, you should be able to reproduce the issue here:
`https://www.msn.com/nb-no/helse/`

**Comment by dnmTX** [comment] 2018-03-15 22:54
@THEtomaso  still ok
![msn helse og trening - helse ernaering trening styrke cardio](https://user-images.githubusercontent.com/34774426/37495126-e7c505bc-2879-11e8-8bd8-1e4d3dc8fe0c.png)

**Comment by StevenBlack** [comment] 2018-03-15 22:55
@THEtomaso just checking here... you understand that "blocking elements" is the whole point of the this hosts file.  Elements coming from ad servers are explicitly blocked.

We have a new release just now because I couldn't get to `msn.com` at all with the hosts file from Release 1.3.1.

**Comment by THEtomaso** [comment] 2018-03-15 23:06
> still ok

LOL!
The site changes faster than I can post!! :)
For me, the issue takes hold at the link that I provided in the first post again now.
If you aren't able to reproduce, try browsing through some of the other sub categories.
Examples:
```
https://www.msn.com/nb-no/livsstil/
https://www.msn.com/nb-no/matogdrikke/
https://www.msn.com/nb-no/nyheter/
```

**Comment by THEtomaso** [comment] 2018-03-15 23:36
OK, here's how to reproduce properly!
Instead of directly opening the subpages that I posted links to before, go to the main page instead, then click on the navigation bar button shown in this screenshot:
![msn2](https://user-images.githubusercontent.com/9382674/37496313-ad1282e8-28a9-11e8-9c83-40aaf2579b55.jpg)

**Comment by dnmTX** [comment] 2018-03-15 23:44
@THEtomaso ok  i see what you mean.Now the question is did you try after @StevenBlack  updated the hosts file(like probably 10 min ago)? Another thing is that i'm almost positive that the blocked element is just another add and nothing important.

**Comment by THEtomaso** [comment] 2018-03-15 23:52
When updating the filter from uBlock Origin, I still get this version:
> Last updated: Thu, 15 Mar 2018 at 09:11:53 GMT

All of the blocked elements seems to be ordinary MSN articles, but it looks like they're kept in a container which also may be used for ads.
After adding my proposed fix, the ads themselves are still efficiently blocked by other rules though.

**Comment by dnmTX** [comment] 2018-03-16 00:01
adnxs.com domain is present at @StevenBlack' lists on many occasions and he didn't remove them.They are there for a reason so updating you filter won't solve your problem.The best thing to do is to make custom rule as you suggested in your first post also advise users in the uBlock forum to do the same as a workaround.

**Comment by THEtomaso** [comment] 2018-03-16 00:18
> adnxs.com domain is present at @StevenBlack' lists on many occasions

I've updated my first post, narrowing it down a bit.

**Comment by StevenBlack** [comment] 2018-03-16 00:29
To clarify, `adnxs.com` is blocked via 

* mvps.org
* someonewhocares.org
* yoyo.org

I'm going to state, flat out, if you want `adnxs.com` delivered to your browser, then this hosts file is **definitely** not for you.

Can I close this issue?  I plan no further action on this.

**Comment by THEtomaso** [comment] 2018-03-16 00:36
No problem.
Thanks for your time.

**Comment by tyzbit** [comment] 2018-03-16 00:36
For what it's worth, maybe it could be removed from my list in the name of narrowing its scope?

**Comment by dnmTX** [comment] 2018-03-16 00:37
@StevenBlack  very much agreed on the "closing" part

**Comment by dnmTX** [comment] 2018-03-16 00:37
@tyzbit no need, it's a tracking domain for sure

**Comment by StevenBlack** [comment] 2018-03-16 00:42
Thanks, folks.  Closing.

**Closed by StevenBlack** 2018-03-16 00:42 UTC
