### ISSUE TITLE
Google Display ADs from google are not being blocked.

### ISSUE THREAD

**Issue by robertjamesm** [StevenBlack/hosts#2412] opened 2023-08-15 19:01 UTC
Google Display ADs from google are no longer being blocked.

**Comment by iam-py-test** [comment] 2023-08-15 21:40
Do you see these on Google search, or another website? What browser/OS are you using?
Can you share a screenshot and a URL where these ads appear?
Thanks

**Comment by StevenBlack** [comment] 2023-08-16 21:01
This is a duplicate of #2407.

@robertjamesm you won't be posting or participating here anymore.

**Closed by StevenBlack** 2023-08-16 21:01 UTC
