### ISSUE TITLE
Instagram does not load 

### ISSUE THREAD

**Issue by inbalboa** [StevenBlack/hosts#2527] opened 2023-12-14 09:36 UTC
www.instagram.com in https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts

Seriously?

**Comment by StevenBlack** [comment] 2023-12-15 14:06
Thank you for this Serhiy @inbalboa.

We do not list the domain `www.instagram.com` in that list.

Closing.

**Comment by TwisX** [comment] 2023-12-15 14:27
If you open the file and do a search, it's definitely there! I use this list and it's there as well: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts

Had to whitelist `www.instagram.com` in pfBlockerNG.

**Comment by StevenBlack** [comment] 2023-12-15 20:44
@TwisX and @inbalboa you are right and I am mistaken.

I am reopening this issue.

The issue is upstream. Ping @sinfonietta — can you please review the inclusion of domain `www.instagram.com` in the porn list? Thanks.

**Comment by Sinfonietta** [comment] 2023-12-16 18:22
@StevenBlack I have just merged a PR that removes this.

**Comment by ScriptTiger** [comment] 2024-11-14 05:28
Just reading through the issues and this one appears to have already been resolved.

**Closed** 2024-11-14 15:32 UTC
Labels: upstream
