### ISSUE TITLE
Spotify on iOS doesn't work properly: spclient.wg.spotify.com blocked

### ISSUE THREAD

**Issue by notDavid** [StevenBlack/hosts#507] opened 2018-02-20 14:04 UTC
https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews/hosts -> line 55772 (and also in other files.)

Whitelisting `spclient.wg.spotify.com` solved the problem.
And also, after i removed this item the whitelist again, Spotify still keeps working, so apparently something was cached while i put it on the whitelist...

Anyways, it seems the same issue as https://github.com/StevenBlack/hosts/issues/270#issuecomment-311715619 ?

**Comment by funilrys** [comment] 2018-02-20 14:41
Duplicate of #506.

**Comment by StevenBlack** [comment] 2018-02-20 15:05
Thanks @notDavid I just updated this repo and the latest hosts file should be fine now.

**Closed by StevenBlack** 2018-02-20 15:05 UTC
