### ISSUE TITLE
add more sites to porn list

### ISSUE THREAD

**Issue by tukusejssirs** [StevenBlack/hosts#566] opened 2018-04-16 12:03 UTC
I found some porn sites that are not in the list:
```
thelesbianconnection.com
collegesexlives.com
dm.damcdn.net
viplocal-hookups.com
18girlsex.net
teenageslut.net
3dporntubex.info
```

**Comment by ScriptTiger** [comment] 2018-04-17 02:46
Bump, @sinfonietta & @clefspeare13 ^

**Comment by g3n0k0m0** [comment] 2018-04-17 03:17
I'll try my best to help research more obscure porn sites to help contribute to the cause ;)

**Comment by Clefspeare13** [comment] 2018-04-17 05:30
I've added these domains

**Comment by StevenBlack** [comment] 2018-04-17 14:54
This is in the [latest release](https://github.com/StevenBlack/hosts/releases).

Closing.

**Closed by StevenBlack** 2018-04-17 14:54 UTC

**Comment by tukusejssirs** [comment] 2018-04-17 15:41
Thank you all for such a prompt response and fix. ;) :+1:
