### ISSUE TITLE
Block  Host Websites working with Browsec VPN

### ISSUE THREAD

**Issue by DawoodImtiaz** [StevenBlack/hosts#2306] opened 2023-04-24 20:18 UTC
Hi Everyone,

Please provide me a solution how can I make host files block websites with VPN as well. Please help

**Comment by icedterminal** [comment] 2023-04-25 19:36
The issues section for this repo isn't the place for 3rd party software assistance.

In general, by design VPNs use their own DNS to secure your connection to prevent what's called DNS leaks. Check your VPN settings.

**Comment by StevenBlack** [comment] 2023-05-03 03:06
Closing!

**Closed by StevenBlack** 2023-05-03 03:06 UTC
