### ISSUE TITLE
Blocks Skype Messages and Calls

### ISSUE THREAD

**Issue by gonkyouka** [StevenBlack/hosts#127] opened 2016-04-12 03:12 UTC
I went to add these IPs to my host files (both x64 versions win10 and win7 x64) after using it, I have an issue with my Skype. I cannot receive some of my contact's messages and group calls. The Skype on my mobile seem to have no problem receiving the messages and calls at the same time having the phone connected to the same network. And on top of that, my friend also have experienced it after using the same set of IPs on his Mac.

**Comment by StevenBlack** [comment] 2016-04-12 04:25
Are you sure @gonkyouka?

I take several Skype calls every day, and Skype-message all day, for the past couple of weeks at least, using a machine that has the most locked-down version of these hosts files.

Can anybody confirm?

**Comment by gonkyouka** [comment] 2016-04-12 05:18
@StevenBlack Have you tried group calls and/or group messaging? I have no luck in both.

**Comment by berrythesoftwarecodeprogrammar** [comment] 2016-04-12 05:48
add `s.gateway.messenger.live.com` to your whitelist

**Comment by gonkyouka** [comment] 2016-04-12 05:52
@berrythesoftwarecodeprogrammar how do you actually do that?

**Comment by berrythesoftwarecodeprogrammar** [comment] 2016-04-12 06:50
there should be a file called `whitelist` in your directory of this script. if there isnt just create a blank file and add that line. when you use `updateHostsFile.py` it wont add hosts in the whitelist to the final hosts file

**Comment by Gitoffthelawn** [comment] 2016-04-12 07:04
Should this whitelist item be added to any documentation?

**Comment by berrythesoftwarecodeprogrammar** [comment] 2016-04-12 07:21
maybe. there were other issues related to microsoft hosts and i think they were all caused by the tyzbit hosts file. i still think its a useful host file but people should be told what to whitelist to unbreak things maybe

**Comment by gonkyouka** [comment] 2016-04-12 08:02
@berrythesoftwarecodeprogrammar oh great thanks!

**Comment by StevenBlack** [comment] 2016-04-12 15:24
@Gitoffthelawn the whitelist is [documented here](https://github.com/StevenBlack/hosts#how-do-i-prevent-domains-from-being-included).

**Comment by StevenBlack** [comment] 2016-04-12 15:27
@tyzbit can I get you to remove `s.gateway.messenger.live.com` ?

@gonkyouka @berrythesoftwarecodeprogrammar ya I've only been doing 1-on-1 calls so that explains it?

**Comment by tyzbit** [comment] 2016-04-12 15:51
@StevenBlack the only spot where that exists is in the someonewhocares.org host list, and it's commented out at that.

**Comment by StevenBlack** [comment] 2016-04-12 16:12
@tyzbit so it is.  Sorry I should have checked that.  Carry on 😄 .

Alright does anyone have more insight on this, cause I don't experience problems with Skype, and surely it ain't `s.gateway.messenger.live.com`.

**Comment by Gitoffthelawn** [comment] 2016-04-12 19:18
@StevenBlack Sorry, I meant perhaps add to the documentation which specific hosts users may want to whitelist in order to allow specific software to work.

Sometimes a host is worthy of being blocked for most people, but blocking it will cause a specific piece of software to stop working.

**Comment by StevenBlack** [comment] 2016-04-12 19:20
@Gitoffthelawn  so far I'm not aware of anything to document, including what's discussed here.  

The wiki would be a good place for that...

**Comment by Gitoffthelawn** [comment] 2016-04-12 19:40
@StevenBlack Yes, your comment about Skype working for you even with `s.gateway.messenger.live.com` blocked indicates that there could be something else going on for @gonkyouka and @berrythesoftwarecodeprogrammar .  It's a curious issue.  Perhaps everyone involved could specify the version of Skype they are using.

**Comment by berrythesoftwarecodeprogrammar** [comment] 2016-04-13 00:48
for me, group chats just wouldnt work until i whitelisted `s.gateway.messenger.live.com`. my messages wouldnt send and i wouldnt recieve any messages. so i dont know

**Comment by StevenBlack** [comment] 2016-04-13 00:53
But @berrythesoftwarecodeprogrammar the domain `s.gateway.messenger.live.com` currently isn't active in this hosts file.  It's commented out.  Everywhere.  

Please try with the latest version.

**Comment by berrythesoftwarecodeprogrammar** [comment] 2016-04-13 00:55
oh, im not even having the problem anymore. i was just saying thats what i had to do in the past for my skype problems. OP needs to tell us if they are still having the issue and if they are using the latest version

**Comment by StevenBlack** [comment] 2016-04-13 01:04
Closing this.

**Closed by StevenBlack** 2016-04-13 01:04 UTC
Labels: question
