### ISSUE TITLE
click.discord.com on fakenews-gambling-porn

### ISSUE THREAD

**Issue by Thiago-Assis-T** [StevenBlack/hosts#2613] opened 2024-03-27 19:44 UTC
I am using the http://sbc.io/hosts/alternates/fakenews-gambling-porn/hosts file, with an auto update script that autofetches the file for me, today i was login in discord and recived the confirmation e-mail, however i was unable to login, because the email link is to click.discord.com, i disabled the host file and logged in, but I wanted to make sure that click.discord.com was there intentionally. I chose the one with no social media blocking because of reddit and discord. the regular discord domain remais unaffected.

**Comment by iam-py-test** [comment] 2024-03-28 19:31
I am sorry, but this is by design. click.discord.com is primarily used for tracking. As such, [StevenBlack does not intend to allowlist it](https://github.com/StevenBlack/hosts/issues?q=click.discord.com).
Please either allowlist it on your devices, or request Discord stop using this domain to tracking links in their emails.
Thank you

**Comment by StevenBlack** [comment] 2024-03-29 00:28
Thank you for this @Thiago-Assis-T, and thank you for the assist @iam-py-test.

As stated above, this isn't going to change.

Closing.

**Closed by StevenBlack** 2024-03-29 00:28 UTC

**Comment by Thiago-Assis-T** [comment] 2024-03-31 00:03
I see, thanks and sorry for not searching the issues and prs...
at the time it didn't seem like intentional, but now explained it does make sense!
