### ISSUE TITLE
loteriasyapuestas.es is a legitimate lottery business run by the country's Treasury since 1811 and shouldn't be blocked

### ISSUE THREAD

**Issue by Deses** [StevenBlack/hosts#935] opened 2019-03-19 19:30 UTC
I've said pretty much everything in the title, lol.

Affected hosts are:
  loteriasyapuestas.es
   juegos.loteriasyapuestas.es
   www.loteriasyapuestas.es
   www.juegos.loteriasyapuestas.es

Which they are present in the gambling list. **Now that's the issue...** Yeah, its lottery... but it's run by the government and the site is very safe, you need ID verification and all that good stuff.

I think it should be removed, IMO, but I would understand if you want to keep blocking it.

https://en.wikipedia.org/wiki/Loter%C3%ADas_y_Apuestas_del_Estado

**Comment by StevenBlack** [comment] 2019-03-19 20:59
Hi Carlos @Deses.

These `loteriasyapuestas` domains do not appear in our vanilla hosts files.

The `loteriasyapuestas` domains only appear in the "gambling" variants of our base hosts files.

```
./alternates/gambling/hosts
./alternates/gambling-social/hosts
./alternates/gambling-porn/hosts
./alternates/fakenews-gambling-porn-social/hosts
./alternates/gambling-porn-social/hosts
./alternates/fakenews-gambling-social/hosts
./alternates/fakenews-gambling/hosts
./alternates/fakenews-gambling-porn/hosts
```

Which is perfect.  This is all by design.

Closing.

**Closed by StevenBlack** 2019-03-19 20:59 UTC
