### ISSUE TITLE
error in hostnames

### ISSUE THREAD

**Issue by ulrichwisser** [StevenBlack/hosts#2213] opened 2023-01-18 09:12 UTC
For my pihole installation I have subscribed to  https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

The latest version of pihole complains about some invalid domain names in the list.

``` [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 168834 domains, 15 domains invalid!
      Sample of invalid domains:
      - 0.0.0.0
      - broadcasthost
      - fe
      - ff
```

After checking in the file I found this

```
#<localhost>
0.0.0.0 fe #00::0 ip6-localnet
0.0.0.0 ff #00::0 ip6-mcastprefix
#fe80::1%lo0	localhost
#</localhost>
```

There seems to be some error in this. I would suggest 

```
# The following lines are desirable for IPv6 capable hosts
0.0.0.0 fe00::0 # ip6-localnet
0.0.0.0 ff00::0 # ip6-mcastprefix
0.0.0.0 ff02::1 # ip6-allnodes
0.0.0.0 ff02::2 # ip6-allrouters
0.0.0.0 ff02::3 # ip6-allhosts
```

**Comment by joaoluizmf2** [comment] 2023-01-18 11:18
Same here:

  **[i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [i] Using libz compression

  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 168834 domains, 15 domains invalid!
      Sample of invalid domains:
      - 0.0.0.0
      - broadcasthost
      - fe
      - ff
  [i] List stayed unchanged**

**Comment by StevenBlack** [comment] 2023-01-18 15:43
This is a duplicate of

* #2207
* #2208
* #2212 

This is a Pi-Hole issue, downstream from us.  They are [working on resolving this](https://discourse.pi-hole.net/t/fresh-install-steven-black-list-invalid-domains/60523/22). 

Closing.

**Comment by ulrichwisser** [comment] 2023-01-18 16:29
Unfortunately this is not correct. I agree with you on all the single label host files, very bad handling on the pihole side.
But 
```
0.0.0.0 fe #00::0 ip6-localnet
0.0.0.0 ff #00::0 ip6-mcastprefix
```
is most definitely wrong on your end. it should be 
```
0.0.0.0 fe00::0 # ip6-localnet
0.0.0.0 ff00::0 # ip6-mcastprefix
```

**Comment by StevenBlack** [comment] 2023-01-18 16:49
Hi Ulrich @ulrichwisser 

Where do you get the limes quoted above ⬆️ ? 

Our hosts files begin with...

```
127.0.0.1 localhost
127.0.0.1 localhost.localdomain
127.0.0.1 local
255.255.255.255 broadcasthost
::1 localhost
::1 ip6-localhost
::1 ip6-loopback
fe80::1%lo0 localhost
ff00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
0.0.0.0 0.0.0.0
```

**Comment by ulrichwisser** [comment] 2023-01-18 18:29
Line 161365 (search for " fe" without quotes)

**Comment by StevenBlack** [comment] 2023-01-18 18:45
Good catch Ulrich @ulrichwisser that's a bug in our parsing routines.

Input lines:
```
fe00::0		ip6-localnet
ff00::0		ip6-mcastprefix
```

Output lines
```
0.0.0.0 fe #00::0 ip6-localnet
0.0.0.0 ff #00::0 ip6-mcastprefix
```

On first glance, weird bug.

**Comment by XhmikosR** [comment] 2023-01-25 07:38
Does anybody have any ideas why this started to happen?

I don't see any related commit that could have affected parsing :/

Maybe something changed on the machine the lists are generated? Python/pip packages?

**Comment by StevenBlack** [comment] 2023-01-26 02:54
I've been wondering the same thing @XhmikosR.

The lines...

```
e00::0		ip6-localnet
ff00::0		ip6-mcastprefix
```

... have been in the `someonewhocares` list for a long time.

* We did not have this issue in Release 3.5.3 (commit 261acf1dfab01a9a54223846f2c2ec4bdd5437a0) which was the last 3.5 release on Mar 28, 2021.
* The very next release, Release 3.6.0, exhibits this problem.

The code changes that triggered the 3.6 minor release were Nissar's @funilrys:
  * https://github.com/StevenBlack/hosts/commit/7971a0cbc91adb86b771561ddf19a03cb687a7dc (*Introduction of the support of RAW lines.*) on Mar 31, 2021, most probably. Release 3.6.0 happened a little later on the same day.

Presently our code uses regexp to assess whether the line's first token is an IPv4 address. To support IPv4 `or` IPv6 is gonna be an unappetizing regexp if we stay with that.

**Comment by XhmikosR** [comment] 2023-01-26 05:34
I just updated to the latest pi-hole and the error seems to be gone. Can someone else confirm?

**Comment by StevenBlack** [comment] 2023-01-26 05:40
@XhmikosR Pi-Hole has since changed its verbocity when it encounters invalid domains when importing hosts files. It's dialed-back the messages. That's presuming you're running a very recent version of Pi-Hole.

**Comment by hugovidafe** [comment] 2023-01-27 02:27
> I just updated to the latest pi-hole and the error seems to be gone. Can someone else confirm?

PiHole updated to last version, executed `pihole -g`, continue appearing:
![image](https://user-images.githubusercontent.com/69076992/214997258-206d7236-e0e7-4364-8542-ecc3b2a0a3e1.png)

**Comment by StevenBlack** [comment] 2023-01-28 03:54
Commit b676693b0cbcd72ceaf941736375614da900e4d5 fixes the IPv6 address facets of this.

Thank you everybody for your input! 🚀 

Closing.

**Closed by StevenBlack** 2023-01-28 03:54 UTC
Labels: bug
