### ISSUE TITLE
Reddit-Domains over-blocked in gambling-social

### ISSUE THREAD

**Issue by Rode-Ven** [StevenBlack/hosts#1047] opened 2019-09-11 09:10 UTC
Access to reddit.com seems to be blocked completely.

I am using https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-social/hosts
Before last weekend, I was able to access pages from reddit.com without problems.
I automatically update the list once a week on Saturday afternoons, and was not able to access ANY page on reddit.com since. I just did a manual update - no change.

While other source block lists contain considerably fewer entries for 'reddit' (e.g. I found only seven entries in Easyprivacy), a quick perusal of the above hosts file reveals well over 50 domains containing  'reddit' somewhere in the name, including www.reddit.com itself.

With the current list, Reddit is completely inaccessible.

**Comment by StevenBlack** [comment] 2019-09-11 10:24
Reddit is blocked by the social media extension, yes.  This is by design.  

Are you saying Reddit is not a social media site?  Well, it is.

Closing.

**Closed by StevenBlack** 2019-09-11 10:24 UTC
