### ISSUE TITLE
Invalid domains in hosts for Pi-hole

### ISSUE THREAD

**Issue by thomasmerz** [StevenBlack/hosts#2208] opened 2023-01-16 11:13 UTC
My Pi-hole told me that there are some invalid domains in your list:

Health status of this list: | List download was successful (OK)
-- | --
This list was added to Pi-hole | 2 years ago (2020-11-03 15:41:19)
Database entry was last modified | a year ago (2021-11-15 12:16:39)
The list contents were last updated | 5 hours ago (2023-01-16 07:15:50)
Number of domains on this list: | 168834
Number of invalid domains on this list: | 15

But it doesn't tell me all invalid domains in detail:
```
  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [i] Status: Pending...^MESC[K  [✓] Status: Retrieval successful
  [i] Analyzed 168834 domains, 15 domains invalid!
      Sample of invalid domains:
      - 0.0.0.0
      - broadcasthost
      - fe
      - ff
  [i] List stayed unchanged
```

I guess:
```
127.0.0.1 localhost
127.0.0.1 localhost.localdomain
127.0.0.1 local
255.255.255.255 broadcasthost
::1 localhost
::1 ip6-localhost
::1 ip6-loopback
fe80::1%lo0 localhost
ff00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
0.0.0.0 0.0.0.0
```

Is there a more Pi-hole-friendly host-list or do you/we really need this localhost-section?

**Comment by hagezi** [comment] 2023-01-16 12:57
This seems to be a bug in the current version of Pi-hole. The entries are valid for host files.

**Comment by StevenBlack** [comment] 2023-01-16 14:15
Hello Thomas @thomasmerz and thank you for the assist Gerd @hagezi.

Operating systems have different default hosts files.  See [this Gist](https://gist.github.com/ghoneycutt/e531984406b4b86ace687ea8958a6dc3) for some examples.

Our hosts files are designed to work on any OS, and on almost any device. Well, insofar as that is possible 😄 

So that explains the top sections of our amalgamated hosts files.

This issue is a duplicate of #2207, closed yesterday.

**Closed by StevenBlack** 2023-01-16 14:15 UTC

**Comment by thomasmerz** [comment] 2023-01-17 18:21
ℹ️ see https://github.com/pi-hole/pi-hole/pull/5009 - this "invalid domains" message is due to the hostnames (not domainnames) and it's a feature/info and not a bug/error 🤣

**Comment by hagezi** [comment] 2023-01-17 21:28
@thomasmerz 
An absolute tour de force. What does such an error message bring to the Pi-hole end user during the Gravity update, except pure confusion? It has absolutely zero added value for the user.
They support the host format, then they should do it in its entirety.

**Comment by thomasmerz** [comment] 2023-01-17 22:51
Agree, but the people at https://github.com/orgs/pi-hole/people really like this feature… 🤷🏼‍♂️ As you can see: I was confused, too…

**Comment by thomasmerz** [comment] 2023-01-23 16:49
I like the solution that the Pi-hole team had brought to us: https://github.com/pi-hole/pi-hole/pull/5128
Because now it's not "something wrong" anymore, but only "an info in a footnote" 😆
