### ISSUE TITLE
Gumroad is blocked as porn

### ISSUE THREAD

**Issue by ryanccn** [StevenBlack/hosts#2539] opened 2023-12-26 03:15 UTC
Gumroad is used for selling a wide range of things including software, merch, etc. However, the blocking of `app.gumroad.com` blanket blocks anything on Gumroad since Gumroad checkouts are done on `app.gumroad.com`.

**Comment by StevenBlack** [comment] 2023-12-26 03:30
Hi Ryan @ryanccn thank you for this.

As far as I can tell, the domain `app.gumroad.com` is in the porn list variants only. That's a limited blast radius 😓 but still.

The issue is upstream. Ping @sinfonietta can you please urgently have a look? Thanks!

**Comment by Sinfonietta** [comment] 2024-01-04 03:10
@StevenBlack the `app.gumroad.com` domain is removed now.

**Comment by StevenBlack** [comment] 2024-01-04 03:18
Thank you @Sinfonietta and thank you for making this issue Ryan @ryanccn.

Closing.

**Closed by StevenBlack** 2024-01-04 03:18 UTC
Labels: upstream
