### ISSUE TITLE
crashlytics.com

### ISSUE THREAD

**Issue by aravindvnair99** [StevenBlack/hosts#1566] opened 2021-03-07 08:54 UTC
[Firebase Crashlytics](https://firebase.google.com/products/crashlytics) is a lightweight, realtime crash reporter that helps developers track, prioritize, and fix stability issues that erode app quality. Crashlytics saves developers troubleshooting time by intelligently grouping crashes and highlighting the circumstances that lead up to them.

I don't think Crashlytics should be blocked. It's used in various apps and is useful for a lot of developers.

**Comment by lightswitch05** [comment] 2021-03-07 12:33
Duplicate of #896

**Comment by aravindvnair99** [comment] 2021-03-07 13:17
> Duplicate of #896

@lightswitch05 Yes I did see that, but just wanted to discuss and get some insights.

I couldn't find any link between advertising and crashlytics. And I feel there's a difference between good telemetry and bad telemetry. I only see Google Analytics linked to Google Crashlytics in the following manner as described at https://firebase.google.com/docs/crashlytics/start-using-analytics, but yes customisation options are available https://firebase.google.com/docs/crashlytics/customize-crash-reports.

**Comment by lightswitch05** [comment] 2021-03-07 13:23
You might be interested in #1346 - personally I don't get into the moral good vs. bad tracking and think that should be left up to the end user. Just proving some links to discussions that might give you further insight as to why the original ticket was closed.

**Comment by StevenBlack** [comment] 2021-03-08 15:45
Thank you for this Aravind @aravindvnair99 

Crashlytics stays blocked.  Last time I looked, despite "crash" in their domain name, crashlytics hoovers bandwidth all the time.  Or at least, that's my last data point.

I'm willing to be convinced otherwise. Big hill to climb to convince me otherwise because they are so bad.

**Comment by StevenBlack** [comment] 2021-03-09 19:58
Closing.

**Closed by StevenBlack** 2021-03-09 19:58 UTC
