### ISSUE TITLE
wpnrtnmrewunrtok.xyz requires whitelisting

### ISSUE THREAD

**Issue by Eow2022yia** [StevenBlack/hosts#2393] opened 2023-07-29 12:19 UTC
Video streams at camwhores.tv are being blocked:

This is due to the following domains being blocked:

wpnrtnmrewunrtok.xyz
camvideo.wpnrtnmrewunrtok.xyz
camvideo12.wpnrtnmrewunrtok.xyz

Steps to reproduce:
Tried to load videos with wpnrtnmrewunrtok.xyz and sub-domains whitelisted, videos load successfully.

Thank you.

**Comment by StevenBlack** [comment] 2023-07-29 17:08
Thank you for this @Eow2022yia.

The domain `wpnrtnmrewunrtok.xyz` comes to us from upstream at yoyo.org.  Please make your case with an email to pgl@yoyo.org.

**Comment by Eow2022yia** [comment] 2023-07-29 17:12
> Thank you for this @Eow2022yia.
> 
> 
> 
> The domain `wpnrtnmrewunrtok.xyz` comes to us from upstream at yoyo.org.  Please make your case with an email to pgl@yoyo.org.

Hi there,

Thanks for your response,

Can this be dealt with on here please?

Thank you.

**Comment by StevenBlack** [comment] 2023-07-29 17:13
@Eow2022yia no, this isn't going to change here.  The issue is upstream.

**Comment by Eow2022yia** [comment] 2023-07-29 18:30
> @Eow2022yia no, this isn't going to change here.  The issue is upstream.  

I'm sorry, I don't understand what upstream has to do with a blocklist filter rule?

Could you explain further for me please?

Thanks.

**Comment by StevenBlack** [comment] 2023-07-29 18:34
@Eow2022yia this is all exolained in the readme. You should read it.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to yoyo.org as I suggested four panels above ⬆️.

I'm certainly not gonna make any expceptions for camwhores.tv, ffs I mean, c'mon 🙄 

Closing and locking this now.

**Closed by StevenBlack** 2023-07-29 18:34 UTC
Labels: upstream
