### ISSUE TITLE
Redirect to playamo.com

### ISSUE THREAD

**Issue by rafops** [StevenBlack/hosts#981] opened 2019-05-20 20:13 UTC
dupinmonig.weebly.com is redirecting to playamo.com

**Comment by spirillen** [comment] 2019-05-25 23:24
Hi @rafops I can't reproduce that, i get i ordinary page

So could you please elaborate that?

![Screenshot_2019-05-26 Imreu](https://user-images.githubusercontent.com/44526987/58375503-ab558600-7f54-11e9-8800-5488f738f776.png)

**Comment by rafops** [comment] 2019-05-30 16:26
Hi @spirillen, please check again because I get a full set of [HTTP redirects](https://trello-attachments.s3.amazonaws.com/5cf0035bde14ec10d23780e8/5cf00363bf5669556fee6e88/77117339846579367bec02a18170cede/playamo.mov). Also the print above shows a page that is pure gibberish or at least considered valid content for a search engine indexing.

**Comment by StevenBlack** [comment] 2019-05-30 17:42
Hi Rafael @rafops  – thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.

**Closed by StevenBlack** 2019-05-30 17:42 UTC

**Comment by funilrys** [comment] 2019-05-30 18:10
Just my input on this if you allow me Steve @StevenBlack,

For me my browser is redirected:

1. http://dupinmonig.weebly.com/
2. https://slink.fun/index.php?id=5c8c1c7d65f72&tpl=sp
3. https://registeramo.com/?refer=b1525e23&ctag=5cf019a9be82b60001aa2759
4. https://www.playamo.com/?refer=b1525e23&ctag=5cf019a9be82b60001aa2759&__layerref=https%3A%2F%2Fslink.fun%2Findex.php%3Fid%3D5c8c1c7d65f72%26tpl%3Dsp

It's really unlikely that it was blocked without any reason ...

**Comment by StevenBlack** [comment] 2019-05-30 18:14
Hi Nissar @funilrys!

We don't presently block `dupinmonig.weebly.com` or `playamo.com`.

I'd prefer to delegate to curators...

**Comment by funilrys** [comment] 2019-05-30 18:48
I know Steve @StevenBlack, 

it was just to clarify that probably a lot of people don't want those behavior to be whitelisted ... It was more for OP than you :wink:

**Comment by rafops** [comment] 2019-05-30 22:30
@StevenBlack, thanks for clarifying. I'll create a PR with one of the curators.

**Comment by StevenBlack** [comment] 2019-05-30 22:39
Thank to Rafael @rafops!  You have a great Github username, by the way.

**Comment by spirillen** [comment] 2019-06-03 00:15
> Hi @spirillen, please check again because I get a full set of [HTTP redirects](https://trello-attachments.s3.amazonaws.com/5cf0035bde14ec10d23780e8/5cf00363bf5669556fee6e88/77117339846579367bec02a18170cede/playamo.mov). Also the print above shows a page that is pure gibberish or at least considered valid content for a search engine indexing.
> True


Hi @rafops , thx for your response and you too @funilrys however I'm unable to reproduce the behavior you both experience :/ and your link is "Access Denied" :disappointed: 

So @rafops could i ask you to post any information you can find on this to my [Gitlab board](https://gitlab.com/dns-firewall/dns/matrix/matrix/issues) to get them blocked?

(Sorry @StevenBlack but GitHub lack of a "chat")

**Comment by spirillen** [comment] 2019-06-03 00:22
typically... :unamused: just as I'm done typing the first redirect appears

```
https://slink.fun/index.php?id=5c8c1c7d65f72&tpl=sp
```
