### ISSUE TITLE
https for hosts file?

### ISSUE THREAD

**Issue by patrickdrd** [StevenBlack/hosts#789] opened 2018-09-27 07:17 UTC
so after adaway's latest version (4.0.9),
we are blocked from using http hosts sources,
which renders sbc.io/hosts/hosts unusable,
is there an alternate url we can use?

**Comment by anudeepND** [comment] 2018-09-27 07:29
@patrickdrd It is being discussed [here](https://github.com/StevenBlack/hosts/issues/788). I would suggest you to close the issue since the issue already exists.

**Comment by funilrys** [comment] 2018-09-27 07:32
@StevenBlack Please close.

Duplicate of #788.

**Closed** 2018-09-27 07:35 UTC
