### ISSUE TITLE
Create coin mining sites blocklist

### ISSUE THREAD

**Issue by xpavli44** [StevenBlack/hosts#499] opened 2018-02-14 12:01 UTC
There should be a new blacklist for coin mining sites. They are abusing computer resources in a similar way to ads.

Source of addresses can be found here
https://github.com/keraf/NoCoin/blob/master/src/blacklist.txt

**Comment by StevenBlack** [comment] 2018-02-14 16:30
Hi @xpavli44 thank you for this suggestion.

The problem, with [NoCoin](https://github.com/keraf/NoCoin/blob/master/src/blacklist.txt) is their data isn't in a compatible format.  Plus it uses wildcards, etc.

Plus, this is a duplicate of #462.  So closing.

**Closed by StevenBlack** 2018-02-14 16:30 UTC
