### ISSUE TITLE
Blocking api.*.immobilienscout24.de prevents mobile app from working

### ISSUE THREAD

**Issue by carcinoma** [StevenBlack/hosts#1136] opened 2020-01-28 14:45 UTC
Since 14.01.2020 the following entries have been added to the hosts file:

> # [immobilienscout24.de]
> 0.0.0.0 api.finanzen.immobilienscout24.de
> 0.0.0.0 api.mobile.immobilienscout24.de
> 0.0.0.0 api.recommendation.immobilienscout24.de

Having these entries will result in a not working mobile app provided by the "immobilienscout24.de"-company.

Is there a specific reason why these domains are blocked? The do not look like adware or malware domains.

**Comment by ScriptTiger** [comment] 2020-01-29 11:48
```
data\adaway.org\hosts:# [immobilienscout24.de]
data\adaway.org\hosts:127.0.0.1 ads.immobilienscout24.de
data\adaway.org\hosts:127.0.0.1 api.finanzen.immobilienscout24.de
data\adaway.org\hosts:127.0.0.1 api.mobile.immobilienscout24.de
data\adaway.org\hosts:127.0.0.1 api.recommendation.immobilienscout24.de
data\adaway.org\hosts:127.0.0.1 tracking.immobilienscout24.de
data\mvps.org\hosts:0.0.0.0 tracking.immobilienscout24.de
data\mvps.org\hosts:0.0.0.0 ads.immobilienscout24.de
```

It was blocked by two different sources, Adaway and MVPS. From the looks of it, despite this being seemingly a legit real estate company, the problem is they put out their own ads and analytics and don't use a third party to do this for them. Since they are hosting very real ads and analytics, there is a valid reason for them to be blocked, even if they are only doing so for themselves and their own marketing purposes. In the future, if they are not doing so already, it would be easy for them to partner with smaller real estate agencies to provide digital marketing services for them since they already have that infrastructure. This is probably a case for individual whitelisting, since there is no counterargument to deny the existence of ads and analytics here.

**Comment by ScriptTiger** [comment] 2020-01-29 12:05
If you would still like to pursue getting these unblocked, specifically the `api.*.immobilienscout24.de` domains, please contact the Adaway source and open an issue there:
https://github.com/AdAway/AdAway/issues

**Comment by StevenBlack** [comment] 2020-02-03 22:52
Hi @carcinoma — and thank you @ScriptTiger.

Let's see what AdAway does.  I trust them to do the Right Thing here.

**Comment by llacb47** [comment] 2020-02-04 01:33
Removed already @StevenBlack in https://github.com/AdAway/adaway.github.io/commit/fc4c7dcaccfaad47b76f6ace97824b418f6ecebb and https://github.com/AdAway/adaway.github.io/commit/8e7d98dfaaa88abbe8fd4778b22ea7c9c9e87525

**Comment by StevenBlack** [comment] 2020-02-04 03:16
Nice!  Thanks everybody.

Closing!

**Closed by StevenBlack** 2020-02-04 03:16 UTC
