### ISSUE TITLE
beacon.dropbox.com

### ISSUE THREAD

**Issue by luispuerto** [StevenBlack/hosts#822] opened 2018-11-01 14:38 UTC
Hey! 

Why is this beacon.dropbox.com is blocked? seem to be part of the Word/office plugin for macOS. 

Thanks!

**Comment by StevenBlack** [comment] 2018-11-01 17:37
Thanks Luis @luispuerto.

Ping Daniel @lightswitch05.

**Comment by Atavic** [comment] 2018-11-01 18:49
Users can add Dropbox integration in Office 365 for Mac OSX, then create and eventually share files.
The URL in this issue appears as one of the Dropbox [URLs used to host user data](https://www.dropbox.com/help/security/official-domains#URL).

**Comment by StevenBlack** [comment] 2018-11-01 18:59
@Atavic that's a very nice list.  Props to Dropbox for publishing it.  And hopefully maintaining it.

**Comment by Atavic** [comment] 2018-11-01 19:19
The files can only be in Word, Access or Excel format. If the files are personal there's no issues; but office files can actually hide some malicious macro actions. There are various [cases](https://packetstormsecurity.com/search/?q=excel): a tool like [this](https://github.com/securitywithoutborders/hardentools) may help in mitigating non-hardened systems.

**Comment by lightswitch05** [comment] 2018-11-01 20:37
@Atavic maybe I'm blind - but I do not see `beacon.dropbox.com` anywhere in that list.

@luispuerto are you experiencing trouble with that host being blocked? I have dropbox on my mac and I haven't noticed any problems with it being blocked. Could you provide steps to reproduce the issue so that I can verify it causing issues?

**Comment by StevenBlack** [comment] 2018-11-01 20:39
@lightswitch05 
```bash
$ ack -l beacon.dropbox.com
alternates/fakenews/hosts
alternates/fakenews-gambling/hosts
alternates/fakenews-gambling-porn/hosts
alternates/fakenews-gambling-porn-social/hosts
alternates/fakenews-gambling-social/hosts
alternates/fakenews-porn/hosts
alternates/fakenews-porn-social/hosts
alternates/fakenews-social/hosts
alternates/gambling/hosts
alternates/gambling-porn/hosts
alternates/gambling-porn-social/hosts
alternates/gambling-social/hosts
alternates/porn/hosts
alternates/porn-social/hosts
alternates/social/hosts
data/lightswitch05/hosts    <----------
hosts
```

**Comment by lightswitch05** [comment] 2018-11-01 20:41
Sorry Steven, yes it **is** in my list, I meant to say that I do not see it anywhere in [URLs used to host user data](https://www.dropbox.com/help/security/official-domains#URL).

**Comment by luispuerto** [comment] 2018-11-01 20:49
@lightswitch05 I started to experience the issue yesterday and it continued this morning. Every time beacon.dropbox.com was blocked dropbox app disconnected and reconnected after 20” or so. I had Word open with the Dropbox plugin. I’ve closed it and the issue stopped. I have to investigate further.

**Comment by luispuerto** [comment] 2018-11-01 20:58
![screen shot 2018-11-01 at 22 56 34](https://user-images.githubusercontent.com/22882880/47879547-88814a00-de29-11e8-81ec-c58f1047da3e.png)

I opened word again and problem is there again.

**Comment by luispuerto** [comment] 2018-11-01 21:01
I opened a different word document (I created a new one and put it in dropbox). 
![screen shot 2018-11-01 at 22 59 17](https://user-images.githubusercontent.com/22882880/47879699-eca40e00-de29-11e8-874c-713386e19ec2.png)
Every time it tries to connect to beacon.dropbox.com dropbox disconnects for 20-30 segs. It tries to connect every 5-4 mins.

**Comment by StevenBlack** [comment] 2018-11-01 21:05
@lightswitch05 there are service providers I'm willing to trust by default.

Github is certainly one of them.

Dropbox is another.

**Comment by luispuerto** [comment] 2018-11-01 21:09
>@lightswitch05 there are service providers I'm willing to trust by default. ...

@StevenBlack yeah I think the same. For that reason I was asking why in particular is that sub domain blocked.

**Comment by lightswitch05** [comment] 2018-11-01 22:42
@luispuerto thank you for the detailed explanation. A lot of beacon domains are used for tracking, looks like this one is being used for connectivity checking. I’ll remove it as soon as I have time. I’m sorry for my delayed responses, I’ve been having some difficulty with my email provider- not related to hosts blocking 😆

**Comment by StevenBlack** [comment] 2018-11-02 18:16
This is fixed in the [latest release](https://github.com/StevenBlack/hosts/releases) which is live and online now.

Thanks everybody!

Closing.

**Closed by StevenBlack** 2018-11-02 18:16 UTC
