### ISSUE TITLE
Could you check https://knowyourmeme.com?

### ISSUE THREAD

**Issue by pr10n** [StevenBlack/hosts#790] opened 2018-09-27 16:55 UTC
Every time i enter https://knowyourmeme.com my CPU load gets high. Is it just me? I'm thinking about mining or special scripts. Just a suggestion.

**Comment by dnmTX** [comment] 2018-10-01 10:01
@pr10n  there are 2-3 domains that are not in the lists,not sure how "harmful" they are but you can add them and see if it's better.I personally can't reproduce the issue on my end.
`toolbar.complex.com`
`xhr.acrabakasaka.com`
`assets.pinterest.com`
`api.b2c.com`

**Comment by pr10n** [comment] 2018-10-01 10:15
I decided to block the knowyourmeme domain itself. I just thought it'd be good to let you know that I have a CPU load issue with that domain just in case it's a reproducible and fixable issue.

**Comment by ScriptTiger** [comment] 2018-10-01 10:33
Good catch, @dnmTX.
mvps.org hits on stats.complex.com and @lightswitch05 hits on b2c.com, adserver.b2c.com, cdn.adserver.b2c.com, and api-54-190-136-221.b2c.com.

After checking the source, I can only confirm media.complex.com and api.b2c.com as being known domains that should be blocked but aren't, so I'll add those to my current PR. The rest might take some more research.

**Comment by StevenBlack** [comment] 2018-10-01 14:01
This is fixed in #793.  Thanks everybody!

Closing.

**Closed by StevenBlack** 2018-10-01 14:01 UTC

**Comment by dnmTX** [comment] 2018-10-01 17:08
`xhr.acrabakasaka.com` hosts script that brings ads and tracking once it's loaded.This is taken from the script:

![xhr acrabakasaka com](https://user-images.githubusercontent.com/34774426/46303842-99ad1180-c572-11e8-84bb-6c7a1f2fe7e3.png)

![xhr acrabakasaka com1](https://user-images.githubusercontent.com/34774426/46303847-9f0a5c00-c572-11e8-8c04-77653aa55d88.png)

Ping @lightswitch05

**Comment by lightswitch05** [comment] 2018-10-01 17:12
@dnmTX thanks, I already have `acrabakasaka.com` and `a.acrabakasaka.com` in the list, happy to add `xhr.acrabakasaka.com` as well

**Comment by dnmTX** [comment] 2018-10-01 17:16
@lightswitch05  happy to help.Also,can you check `https://civicscience.com/`. Their website is all about surveys,tracking and ads.There is also script from them on that page.

**Comment by mrjackyliang** [comment] 2020-07-23 02:23
Anyone looking for information on "b2c.com", it belongs to [FouAnalytics](https://fouanalytics.com/). Proof [here](https://securitytrails.com/list/ip/44.233.113.241). Took me a couple of weeks!

Oh, and this: [http://pi-hole.b2c.com/admin/](http://pi-hole.b2c.com/admin/) 😂

**Comment by dnmTX** [comment] 2020-07-23 04:09
I can confirm @mrjackyliang's findings and we already know that anything related to `b2c.com` is as bad as it can get.
But i also found this:
https://www.linkedin.com/pulse/fouanalytics-alternative-google-analytics-fraud
so at this point i'm kind of on the crossroad so i'll leave it to Steve @StevenBlack to make the call here.
In case it's approved those are the domains that will need to be blocked:
`0.0.0.0 api.fouanalytics.com`
`0.0.0.0 adsbydomain.fouanalytics.com`

**Comment by mrjackyliang** [comment] 2020-07-23 11:41
Dr. Fou is often on Twitter also. One of the really interesting things I found in their hidden eval code is that it is a fingerprinting mechanism, a very specific one.

**Comment by StevenBlack** [comment] 2020-07-23 14:07
Thanks Jacky @mrjackyliang and Dan @dnmTX, I've added those two `fouanalytics.com` domains in commit 58b36a7e.

**Comment by llacb47** [comment] 2020-07-23 14:09
This website uses the `api.fouanalytics.com` script: `https://thoughtcatalog.com/`

**Comment by ScriptTiger** [comment] 2020-07-24 09:15
@llacb47, the whole premise behind blocking unwanted analytics domains is that you can still connect to the websites you want, but the references to resources hosted at unwanted domains will just get blocked, or more specifically will not be able to resolve those domain names. So you can enjoy the content you want to while also blocking the analytics at the same time. So there is no need to block every website that references hosted analytics scripts from domains already blocked, otherwise none of us would indeed be using GitHub right now, or most other websites for that matter.

Excerpt from `thoughtcatalog.com`:
```
<link rel='dns-prefetch' href='//api.fouanalytics.com' />
...
<script async data-cfasync="false" src='https://api.fouanalytics.com/api/init-787y3di1lxn61yk7x4r.js?ver=1.0.0'></script>
<noscript><img src="https://api.fouanalytics.com/api/noscript-787y3di1lxn61yk7x4r.gif"></noscript>
```

**Comment by dnmTX** [comment] 2020-07-24 09:23
@ScriptTiger, @llacb47  was just informing us where he found `api.fouanalytics.com` and not suggesting the entire website to be blocked because of it. He is pretty knowledgeable how things work and very helpful here 😉

**Comment by ScriptTiger** [comment] 2020-07-24 09:25
Oh, sorry! I read it wrong lol. Yeah, I see you guys are making a list of "evidence" for the case. Okay, okay, sorry :P
