### ISSUE TITLE
the updateHostsWindows.bat script doesn't works as a scheduled task on Windows

### ISSUE THREAD

**Issue by dakd2** [StevenBlack/hosts#551] opened 2018-03-27 01:04 UTC
I have been using steven black hosts in the form of the unified hosts autoupdater, changed the scheduled task script of the autoupdater by the updateHostsWindows.bat script in the hosts-master tree to test the effect of the --compress switch and added my own extensions on the command parameters, the scheduled task says that it completed everyday I boot the computer but the Windows hosts file is intact since last time I updated it

**Comment by ScriptTiger** [comment] 2018-03-27 01:54
I'll take a look at it later. If you have Python installed and all of the other necessary prerequisites, the problem is most likely that the script is a simple one and doesn't account for being executed from a directory other than the one that it is in. When you execute a script as a scheduled task, it's executed either in the user's home directory, system32 directory, or possibly somewhere else depending on your setup. That batch script uses only relative paths:

`python updateHostsFile.py -a`

So when your system runs it from your home profile or the system32 directory, it can't find the updateHostsFile.py there because it's not there, it's in whatever directory it's in and not that one. It needs to include a full path. My AutoUpdate script was written to always know where it is and is a bit more complex.

**Comment by dakd2** [comment] 2018-03-27 17:24
I added the script directory path in the "start in" field of the scheduled task properties->actions, then forced the scheduled task to execute and it updated the Windows hosts file accordinly. before the "start in" field was empty the hosts file wouldn't update everytime I forced the scheduled task to execute

**Comment by StevenBlack** [comment] 2018-03-27 18:20
Closing.

**Closed by StevenBlack** 2018-03-27 18:20 UTC
Labels: Documentation

**Comment by ScriptTiger** [comment] 2018-03-28 03:07
Nice. If you can, please let us know what happens in the other issue on my repo so I can use you as a test case for when I update my script to include a variable length compression option:
https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/issues/5

I already have the code ready and am using it to generate the compressed formats on the website, but am just waiting to get enough verified people with this problem to test it once I implement it since I can't test it myself because I can't replicate the issue.
