### ISSUE TITLE
Blocklist issue: improving.duckduckgo.com

### ISSUE THREAD

**Issue by danieldurrans** [StevenBlack/hosts#1826] opened 2021-12-12 08:34 UTC
This is an issue with the shady-hosts blocklist:

https://github.com/shreyasminocha/shady-hosts/issues/8

Blocking of improving.duckduckgo.com has started to negatively impact the use of duckduckgo.com

Consequence:

- Search results page not fully loading
- Duckduckgo functionally not working

Explicitly whitelisting this domain resolved useability issues with duckduckgo.

This issue was noticed when using a default pihole configuration, pulling a blocklist from https://github.com/StevenBlack/hosts

**Comment by StevenBlack** [comment] 2021-12-12 15:56
Thanks for this Daniel @danieldurrans. Yes that's not a good side-effect.

Shreyas @shreyasminocha can you look into this?  What do you think?

**Comment by shreyasminocha** [comment] 2021-12-12 16:42
I can't seem to reproduce this. I don't have a pihole to test with, but at least search seems to work with `improving.duckduckgo.com` blocked in `/etc/hosts`. I have DuckDuckGo set to its default settings, including "All regions" and "Safe search: moderate".

@danieldurrans Could you please share more details to help reproduce this? A screenshot of the broken page and details of custom settings (if any) would help. If they're A/B testing something new, the region you're browsing from could also be relevant.

**Comment by dnmTX** [comment] 2021-12-12 19:19
@shreyasminocha is this a tracking/telemetry or just annoyance?
If it's the latter it could cause problems and considering the user base here it's probably a good idea to remove it as you literally can't test every scenario or at least will take you really long time doing it.
Just my 2 cents 👍

**Comment by danieldurrans** [comment] 2021-12-12 19:42
Thank you for quickly looking into this issue, much appreciated.

I haven't been able to reproduce the problem this evening (after removing from whitelist and clearing caches). Web searches for the same, similar, and different keywords are not resulting in any DNS queries for improving.duckduckgo.com. Therefore I would be inclined to go with @shreyasminocha's theory that they were a/b testing something new.

Environment:
- Safari 15.1 on OSX 11.6.1
- DuckDuckGo.com with adverts turned off
- Wipr Safari extension
- ActiveTab Safari extension
- 1Password Safari extension
- Location: United Kingdom
- Pi-hole v5.6  FTL v5.11, pointing at a locally hosted recursive dns server 

Steps to reproduce:
1. Search for: catit water fountain motor hum annoying
2. Results page displayed

Symptoms:
- Scrolling down the page would not show any content that wasn't displayed "above the fold"
- Clicking on a search result would serve the search result above the one you click on
- Clicking the "more results" button (when it loaded, if it loaded) did not load any more results

 Things I tried that didn't work
- Disabling Wipr (made no difference)
- Hitting refresh a lot (sometimes the page loaded more results, sometimes it didn't, but page was very non functional)
- Clearing caches
- Clearing DuckDuckGo cookies and locally stored data

Things I tried that did work:
- Used Safari Web Inspector to see if page was complaining about anything. This showed that it was trying and failing to contact improving.duckduckgo.com. I added the domain to my whitelist in pihole, at which point DuckDuckGo functioned correctly again.

**Comment by StevenBlack** [comment] 2021-12-12 23:49
@shreyasminocha I tend to agree with Dan @dnmTX here. If there's any doubt, I'm inclined to suggest cutting duckduckgo some slack. That said, your list, your call.

**Comment by shreyasminocha** [comment] 2021-12-16 07:47
So apparently they use the requests to `improving.` to [track certain page events](https://help.duckduckgo.com/privacy/atb/).

> […] we measure engagement of specific events on the page (e.g. when a misspelling message is displayed, and when it is clicked). This allows us to run experiments where we can test different misspelling messages and use CTR (click through rate) to determine the message's efficacy. If you are looking at network requests, these are the ones going to the one-pixel image at `improving.duckduckgo.com`. These requests are anonymous and the information is used only by us to improve our products

Here are some of the requests DDG makes when I search "foo" and interact with the page a little:

```
https://improving.duckduckgo.com/t/dev?9068658&d=dictionary_definition:module:mainline:triggering:1&q=foo&serp_return=0&organic_above_fold=1&g=__&blay=a1w29i1r1,i1e1w1e1&dsig=dictionary_definition:h&isig=meanings:l&biaexp=b&msvrtexp=b&nadse=b&eclsexp=b
https://improving.duckduckgo.com/t/im_x?7446823&status=error&error=&code=0&g=__&blay=a1w29i1r1,i1e1w1e1&dsig=dictionary_definition:h&isig=meanings:l&biaexp=b&msvrtexp=b&nadse=b&eclsexp=b
https://improving.duckduckgo.com/t/iaui?2278728&oi=dictionary_definition&r1=dictionary_definition&r2=videos&r7=twitter&r9=en_wikipedia_queries,nlp_fathead,nlp_wiki&q=foo&ct=GB&d=d&kl=uk-en&rl=uk-en&g=__&blay=a1w29i1r1,i1e1w1e1&dsig=dictionary_definition:h&isig=meanings:l&biaexp=b&msvrtexp=b&nadse=b&eclsexp=b
https://improving.duckduckgo.com/t/iaoi_dictionary_definition?8870596&ss=0&sp=0&im=1&ism=0&px=0&ul=0&adc=1&timeSincePageLoad=1800&timeSinceDeepStarted=200&timeSinceDeepFinished=200&adn=1&is_good_v8_0=0&is_good_v8_1=0&q=foo&ct=GB&d=d&kl=uk-en&rl=uk-en&kp=-1&serp_return=0&g=__&blay=a1w29i1r1,i1e1w1e1&dsig=dictionary_definition:h&isig=meanings:l&biaexp=b&msvrtexp=b&nadse=b&eclsexp=b
https://improving.duckduckgo.com/t/apss_f?4666638&g=__&blay=a1w29i1r1,i1e1w1e1&dsig=dictionary_definition:h&isig=meanings:l&biaexp=b&msvrtexp=b&nadse=b&eclsexp=b
https://improving.duckduckgo.com/t/l2_d_re?1322895&u=bingv7aa&rc=10&oll=en:23,vi:1&q=foo&ct=GB&rl=uk-en&serp_return=0&organic_above_fold=1&g=__&djsd=0&blay=a1w29i1r1,i1e1w1e1&dsig=dictionary_definition:h&isig=meanings:l&biaexp=b&msvrtexp=b&nadse=b&eclsexp=b
https://improving.duckduckgo.com/t/ias_meanings?8088217&q=foo&ct=GB&d=d&kl=uk-en&rl=uk-en&g=__&blay=a1w29i1r1,i1e1w1e1&dsig=dictionary_definition:h&isig=meanings:l&biaexp=b&msvrtexp=b&nadse=b&eclsexp=b
https://improving.duckduckgo.com/t/l_d_re?8429808&br=firefox&bv=91&iao=1&rl=uk-en&dl=en&ck=1&atbi=false&i=true&q=foo&ct=GB&kl=uk-en&kp=-1&serp_return=0&g=__&djsd=0&blay=a1w29i1r1,i1e1w1e1&dsig=dictionary_definition:h&isig=meanings:l&biaexp=b&msvrtexp=b&nadse=b&eclsexp=b
https://improving.duckduckgo.com/t/iaoi_related_searches?6903574&ss=0&sp=0&im=1&ism=0&px=0&ul=0&adc=1&timeSincePageLoad=1600&timeSinceDeepStarted=0&timeSinceDeepFinished=0&adn=1&is_good_v8_0=0&is_good_v8_1=0&q=foo&ct=GB&d=d&kl=uk-en&rl=uk-en&kp=-1&serp_return=0&g=__&blay=a1w29i1r1,i1e1w1e1&dsig=dictionary_definition:h&isig=meanings:l&biaexp=b&msvrtexp=b&nadse=b&eclsexp=b
https://improving.duckduckgo.com/t/ad_bingv7aa?8522376&n=1&rl=uk-en&sld=1&d=ebay.co.uk&ds=ebay.co.uk&q=foo&ct=GB&kl=uk-en&kp=-1&serp_return=0&g=__&blay=a1w29i1r1,i1e1w1e1&dsig=dictionary_definition:h&isig=meanings:l&biaexp=b&msvrtexp=b&nadse=b&eclsexp=b
https://improving.duckduckgo.com/t/si?8935416&b=firefox&atbi=false&ei=true&i=true&d=d&l=en_US&p=linux&atb=v304-2&va=_&atbva=_&g=__&blay=a1w29i1r1,i1e1w1e1&dsig=dictionary_definition:h&isig=meanings:l&biaexp=b&msvrtexp=b&nadse=b&eclsexp=b
https://improving.duckduckgo.com/t/ias_products?7790248&q=foo&ct=GB&d=d&kl=uk-en&rl=uk-en&g=__&blay=a1w29i1r1,i1e1w1e1&dsig=dictionary_definition:h&isig=meanings:l&biaexp=b&msvrtexp=b&nadse=b&eclsexp=b
```

In terms of precedents, it looks like EasyPrivacy and the Adguard Tracking list block `||duckduckgo.com/t/` which targets all and only `improving.duckduckgo.com` requests from what I can tell. While @danieldurrans' report seems to confirm that `improving.` was responsible for the breakage, I think I want to wait this one out for a little bit. If there are more reports or if we figure out a way to consistently reproduce this, of course, it's gonna have to go.

**Comment by dnmTX** [comment] 2021-12-16 08:17
Looks like they embeded it in another script as well: https://duckduckgo.com/util/u595.js which is responsible to show the search results.
I kind of agree with @shreyasminocha. Let's wait and see. I tested it on my end and all works as intended 👍

**Comment by StevenBlack** [comment] 2021-12-16 15:52
I hate this. Thanks everyone.

Daniel @danieldurrans we're going to sit on this for awhile. I think I partly understand what duckduckgo is doing here, but need to cross-reference all this with what they say — and what they don't say — in their policies.

Leaving this open.

**Comment by dnmTX** [comment] 2021-12-17 08:55
Hmmm.....similar issue poped up at [anudeepND's list](https://github.com/anudeepND/blacklist/issues/183) 🤔

**Comment by mullasci** [comment] 2022-02-01 04:59
I had no problem with the images until yesterday, but now it's the case also for me.
I checked it's pihole blocking the domain.

As others mentioned the search safety setting makes no difference and the images just load fine if a different search engine is used.

**Comment by StevenBlack** [comment] 2022-02-01 17:15
Thanks @shreyasminocha!

Daniel @danieldurrans this will eb reflected in the next release, coming shortly. Thank you for reporting this.

Closing.

**Closed by StevenBlack** 2022-02-01 17:15 UTC
Labels: monitor (ongoing), discussion, need broader input

**Comment by danieldurrans** [comment] 2022-02-01 18:13
Fantastic, thank you @StevenBlack
