### ISSUE TITLE
Latest pihole considers some domains invalid

### ISSUE THREAD

**Issue by SamTV12345** [StevenBlack/hosts#2212] opened 2023-01-17 16:37 UTC
When starting the dockerhub image of pihole/pihole:latest it contemplates 15 domains as invalid. Unfortunately I couldn't find a hint which domains are invalid.

How to reproduce:
- `docker run pihole/pihole`
- Check out the startup logs

**Comment by StevenBlack** [comment] 2023-01-17 17:24
Hi @SamTV12345 thank you for this.

This issue is a duplicate of

* #2208 
* #2207 

This is a Pie-hole issue; they are downstream from us. We're serving valid hosts files here.

**Closed by StevenBlack** 2023-01-17 17:24 UTC
