### ISSUE TITLE
Update 'Third-Party Hosts Managers for Windows'

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [StevenBlack/hosts#400] opened 2017-08-24 16:43 UTC
As the homepage for HostMan is down, I think it would be a good idea to update some parts in the README.md and to suggest some other apps for Windows there, too.
I will try to make a PR if the changes are welcome.

CC: Issue #370 , #380

**Comment by ScriptTiger** [comment] 2017-08-24 17:11
The HostsMan site isn't down. The URL is:

http://www.abelhadigital.com/hostsman

If you can't view it, it's probably because you're using you're own local DNS server and/or have DNS-related firewall configurations and you can't resolve it. Try pointing your machine to 8.8.8.8 and/or 8.8.4.4 and/or disabling your firewall temporarily to see if  you can access it directly. Or you can just try using a proxy:

https://www.proxysite.com/

**Comment by ScriptTiger** [comment] 2017-08-24 17:19
Oh yeah, and don't forget to plug your app:

https://github.com/LV-Crew/HostsManager/releases

The LV-Crew is seeking feedback on their HostsManager, so check it out and let us and them know what you think.

**Comment by Tobias-B-Besemer** [comment] 2017-08-24 17:49
I got an error from my 404-Extension...

And @ScriptTiger, you probably mixed @grantcarthew and me in you last comment in Issue #370...
...so I'm a bit confused of what you writing...
![2017-08-24 19_44_22-nightly](https://user-images.githubusercontent.com/11881073/29680489-fb768e1a-8904-11e7-8c6b-1a0737abb34f.png)

**Comment by ScriptTiger** [comment] 2017-08-24 22:56
404 means your machine cannot find the website, but there can be many reasons why. It can be because the website is down or because your machine cannot find the website, it does not mean the same thing. Did you try using a proxy website like https://www.proxysite.com/ and try going to http://www.abelhadigital.com/hostsman? Can someone else verify this so he does not continue to think I am crazy? I am saying this because I already know what the problem is.

Don't worry about grantcarthew, I have never seen him before. I was just telling him to be careful about continuing to push the CR-LF issue because Steven has already made his position clear and he obviously finds it annoying to continue to bring up. And then I was also making a suggestion to you so more people know about your HostsManager because I have actually seen you before and care more about you :P

**Comment by rautamiekka** [comment] 2017-08-24 22:59
http://www.abelhadigital.com/hostsman works fine for me.

**Comment by grantcarthew** [comment] 2017-08-24 23:59
I mostly work in the Node.js/JavaScript community @ScriptTiger and the community is awesome. Everyone is helpful and friendly. Just saying.

So the new script I wrote is relevant to this thread.
It's not downloading a third party tool. It's more like an extension to PowerShell which is built into Windows.

I wrote it for myself and I discovered this hosts file block list in my searching. It was very simple to add an install script so I did so. My post into the CRLF thread was just trying to help.

Anyway, details here: https://github.com/grantcarthew/GCPowerShell and after recent interactions I don't really care if it goes any further than this.

**Comment by ScriptTiger** [comment] 2017-08-25 00:36
I also do work in the Node.js/JavaScript community and I agree, although I don't do it under this account due to job requirements. My issues are nothing personal against you or your script. Since you have not been here before and have not been keeping up with the recent events, I will just let you know that CR-LF has been a bit of a sensitive issue and both issues and PRs have been opened and closed over it many times and Steven has expressed his annoyance more than once. There are only a couple lingering issues related to it left floating around and the one you posted on had already been closed and reopened and was related to a PR that has already been closed. Before plugging your scripts in the future, I would recommend doing an issue search first with no filters for keywords related to what you are plugging and reading a bit to make sure the context is right. And just to reiterate, this is not personal whatsoever. In fact, Steven is from Canada, which is on everyone's top 10 friendliest nations list. It's just out of pure efficacy to keep the workflow running smoothly. I truly hope you understand and good luck!

Now just to circle back to the point of this thread and to stop taking attention away from where it's due, LV Crew's new HostsManager:
https://github.com/LV-Crew/HostsManager/releases

Please give us feedback!

**Comment by StevenBlack** [comment] 2017-08-29 13:32
Closing.

**Closed by StevenBlack** 2017-08-29 13:32 UTC
