### ISSUE TITLE
Malware Domain List is obsolete

### ISSUE THREAD

**Issue by crssi** [StevenBlack/hosts#1403] opened 2020-09-10 08:58 UTC
The last entry was made 3.5 years ago...
see https://www.malwaredomainlist.com/mdl2.php?inactive=&sort=Date&search=&colsearch=All&ascordesc=DESC&quantity=1

I think its safe to remove.... it was also dropped by uBO, see `https://github.com/uBlockOrigin/uBlock-issues/issues/984`

Cheers

**Comment by StevenBlack** [comment] 2020-09-11 14:43
This is a duplicate of Issue #1044.  See in particular, the comments at the end of the issue.

The assertion that malwaredomainlist.com hasn't been updated in 3.5 years is observably incorrect.  Is it as active as we would like?  No.  Is it obsolete?  No.

Closing.

**Closed by StevenBlack** 2020-09-11 14:43 UTC

**Comment by llacb47** [comment] 2020-09-11 14:59
> See in particular, the comments at the end of the issue.

The list was not "updated" in January. One domain was removed. That does not meet the minimum quality standard for an update IMO. No new domains have been added for 2 years according to the maintainer of Nano Adblocker. (https://github.com/uBlockOrigin/uBlock-issues/issues/984#issuecomment-612058511)

https://github.com/uBlockOrigin/uAssets/commit/5ad7faaf9e0337e114ea151f5ef6bb5d6b8ccd8f#diff-53fe5504d16f8ca7c58a72186493bdef
