### ISSUE TITLE
Simplify windows instructions

### ISSUE THREAD

**Issue by inexist3nce** [StevenBlack/hosts#67] opened 2016-02-12 05:39 UTC
You know, there's `win + r` which is way simpler

![](http://www.tech-recipes.com/wp-content/uploads/run-dialog.jpg)

**Comment by pewusoft** [comment] 2016-02-12 08:34
And that's only if you have UAC disabled. However, on Windows >= 7, you can just type cmd in Start menu and press Ctrl+Shift+Enter to run task as admin. Much cleaner and simpler.

**Comment by Zabanya** [comment] 2016-02-12 11:58
on Windows 8 we can Start and type cmd -> Right Click -> Run as Admin as well

**Comment by StevenBlack** [comment] 2016-02-12 13:40
Hey @inexist3nce @pewusoft @Zabanya thanks for the input!

Marking this as `enhancement`.

**Comment by pewusoft** [comment] 2016-02-12 20:07
You're welcome :)

**Comment by reddit-is-fun** [comment] 2016-03-31 20:18
I don't know how to use this script on Windows. On Linux I'd clone the repository and open terminal in that location, on Windows I have no idea. I've extracted the repo and run `updateHostsFile.py`. Hosts file is saved to `hosts-master` folder, but my existing hosts file in `~\Windows\System32\drivers\etc` isn't replaced.
I decided to move the entire `hosts-master` folder content to `~\Windows\System32\drivers\etc`. Now my hosts file gets updated, but I think this isn't a right way at all...

**Comment by StevenBlack** [comment] 2016-03-31 21:08
No, that isn't the right way :smile: though, hey, two points for you for thinking outside-the-box.

The reason the Windows hosts file isn't copied is because the Windows access control story is a monumental cluster.  

Heck, in the Windows VMs I use, I can't even get programs I've manually pinned to the task bar to not notify me of scary dangers every time I invoke them.

Windows is just broken.   You have my sympathies.

**Comment by berrythesoftwarecodeprogrammar** [comment] 2016-04-02 12:22
i just keep a shortcut to `C:\Windows\System32\drivers\etc` in my `hosts` folder so i can visit it quickly after updating and paste the file. could probably even try dragging it into the shortcut

**Comment by reddit-is-fun** [comment] 2016-04-03 16:44
@berrythesoftwarecodeprogrammar Yes, it's relatively easy to circumvent Windows limitations. 
Does the hosts file name need to be capitalized (`HOSTS`) on Windows? The script uses `hosts` by default.

**Comment by pewusoft** [comment] 2016-04-03 20:06
All native Windows filesystems are case insensitive, so you can even write `HoStS` and it should work

**Comment by berrythesoftwarecodeprogrammar** [comment] 2016-04-03 23:29
and the default file on windows is lowercase anyway

**Comment by reddit-is-fun** [comment] 2016-04-04 16:42
@berrythesoftwarecodeprogrammar I guess I made a mistake, HostsMan had generated that file.

**Comment by reddit-is-fun** [comment] 2016-04-22 08:28
Why aren't the domains added to `myhosts` prefixed with `0.0.0.0` in the hosts file? I can't think any reason this shouldn't be the default behavior. I also don't know if this only affects Windows, can't currently test the Linux version.

`C:\Windows\System32\drivers\etc\hosts`:
# Custom host records are listed here.
kotaku.com
www.buzzfeed.com
www.dailymail.co.uk

**Comment by berrythesoftwarecodeprogrammar** [comment] 2016-04-22 12:38
they are on my windows

**Comment by StevenBlack** [comment] 2016-04-22 13:14
Hi @reddit-is-fun this is by design.

`myhosts` is for inclusion, at the top, of legitimate hosts that you may have. such as 

    192.168.17.1 router
    192.168.17.15 printer
    192.168.17.16 media
    192.168.17.17 HueKitchenSouth
    192.168.17.18 HueKitchenNorth

... and whatever

See [How do I include my own custom domain mappings?](https://github.com/StevenBlack/hosts#how-do-i-include-my-own-custom-domain-mappings) in the docs.

Nothing stopping you from putting this in `myhosts`.  That will work too.

   0.0.0.0 www.buzzfeed.com

Point is, `myhosts` isn't mangled, and this is by design.

**Comment by reddit-is-fun** [comment] 2016-04-22 14:17
OK, I understand. And yes, I can start every line with `0.0.0.0`

**Comment by reddit-is-fun** [comment] 2016-04-26 23:36
The last thing that's still unclear to me is using **hosts file variants** on Windows. How can I use one without command line? Do I modify the content of `data/` subfolder?  
I use all `gambling + porn + social` variants on Linux and Android. I would probably

**Comment by StevenBlack** [comment] 2016-04-27 00:03
Hi @reddit-is-fun that's right.  The Python script assembles all the components and creates the unified  files that include your whitelist and your own hosts either as data or as extensions.

If you want to skip that then, yes, open the hosts file in a text editor and include your own.  Or you could write a batch file to combine the files for you.

The Python script is painless....

**Comment by gfyoung** [comment] 2017-05-25 05:48
@StevenBlack : I was reading this over, and I'm not really sure if there is such a concern anymore.  I think the instructions are fairly simple:

* Open command prompt as administrator
* Run updateHostsFile.py
* Copy new host file to location specified by script
* Run `ipconfig /flushdns` command afterwards

These are all specified in the docs / code, so I think this is resolved now?

**Closed** 2017-05-25 14:07 UTC
Labels: enhancement, Windows

**Comment by gfyoung** [comment] 2017-05-25 18:23
Actually, even better just run `updateHostsWindows.bat` as administrator from command prompt :smile:
