### ISSUE TITLE
information - closed pornlist inclusions updates are not blocked - many updates need to be processed

### ISSUE THREAD

**Issue by jobbb2** [StevenBlack/hosts#2399] opened 2023-08-05 09:41 UTC
Hello

I am writing to you because I have not received an answers to my previous questions from Sinfonietta.

On July 6, Sinfonietta marked my pornlist inclusion updates as closed. Today i tested this if its really blocked.
Only the https://github.com/Sinfonietta/hostfiles/issues/243 was blocked.
The other issues https://github.com/Sinfonietta/hostfiles/issues/242, https://github.com/Sinfonietta/hostfiles/issues/241, https://github.com/Sinfonietta/hostfiles/issues/240 and https://github.com/Sinfonietta/hostfiles/issues/239 are not blocked.

And i inform you:
3 weeks ago i wrote to Sinfonietta:
Hello https://github.com/Sinfonietta. Please can you check my new pornlist links and embed them, because there are a lot of links. To avoid that you suddenly have a lot of work with it.. Best regards
Until now i did not receive an answer, maybe she is on vacation etc., no problem. i think this is a voluntary work.
But until now i gave her more than 3600 new pornlist inclusion. I think its a lot of work to check the links and then add it to your blocklist.
I am therefore writing to you, maybe distribute the tasks, to several people, if suddenly many links come in.
Thanks for your great work. Best regards

**Comment by StevenBlack** [comment] 2023-08-05 14:43
@jobbb2 I think you need to understand a few things.

You have created many many issues with lists of porn sites.  Those aren't pull requests, those are issues.  Some of the issues aren't in the appropriate repository; you just "dump" them here, dump them on @sinfonietta, maybe you duplicate dump them?  Who the hell knows? There is no organization, it's just a bunch of uncoordinated, unsynchronized issues.

Each issue is going to involve a workflow. **Each issue actually creates work** for somebody else.

**Here's the work that needs to be done for each issue**:

1) Check the veracity of the links
2) Check for duplicates
3) Check that the issue isn't reported in another place, as may be the case here.
4) Processing the issue
5) Advise some **other** repository owner that the misplaced issue can be closed by keeping track and conveying the issue number form one organization to another.

It's almost the same work whether the issue contains one link, or a thousand links.  **If there are 10-issues, that is 10-times the work**.

You seem completely unaware that, on GitHub, you can edit issues you create. You have always been able to append a list of domains to an existing issue containing a list domains.  But you don't do that. You create new issues, thereby linearly increasing the amount of work required. 

Nobody is getting paid here.  

There are potentially a million yous out there, creating work for volunteers, and then complaining about it.

Here's something else you need to understand.

On a scale of 1 to 10, where a 10 would be a severe threat like a source of malware, and where zero is negligible, a porn domain scores a zero-point-five on that scale.  Extremely low priority.

The mission of some extensions of this project is to keep porn out of someone's life, or out of someone's house, or out of some organization.  The **Pareto Principle** applies here.  Once all the conventional and well known sources of porn are listed, that's already the majority of the porn industry.  Adding 30 obscure low-traffic domains to the 50,000 we already carry is **negligible benefit**.

So what you've done, probably without realizing it, is maximize the work required for the most meager of benefits.

**THE POINT BEING** the goal of the porn extensions is not to list every purveyor of porn on the internet. The goal is to economically keep porn out of people's lives.  In other words, to do the job well enough.

**Comment by jobbb2** [comment] 2023-08-05 18:07
Hello,

the question is what can I do to improve the situation?
I want to copy the links from the open issues and paste them into a pull request. Can I delete the open issues afterwards, or is it enough to delete the content. Is this also possible for the closed issues?
I don't just copy any links I find, I test them. This is really hard and hours of work.

Best regards

**Comment by StevenBlack** [comment] 2023-08-06 01:24
Thank you @jobbb2.

By my reckoning the open issues listed below are yours. 

This repo doesn't curate porn domains but over 16% of all the open issues here are yours, and they are all about porn.  Some of the issues below list **ONE** porn domain.

This project is used by millions directly and indirectly, and you're singlehandedly stinking-up the issues here with stuff that doesn't even belong here.  You create work for me, and then complain about it. Please close all these issues and **YOU**, please, curate these domains and list them with @sinfonietta or @bigdargon or @brijrajparmar27 or @tiuxo, who are all porn curators whose work is included and distributed in our lists.

Open source developers and volunteers get abused and all this fits squarely in this category. I understand that you're trying to help but, at some juncture, this stuff has got to stop.

**PLEASE** re-read what I wrote in a panel above ⬆️⬆️: the goal of the porn extensions lists in this repository is not to list every purveyor of porn on the internet. The goal is to economically keep porn out of people's lives. In other words, to do the job well enough.

* #2381  new suggestion porn blacklist     
* #2379  suggestion porn blacklist         
* #2375  suggestion porn black list        
* #2374  suggestion porn blacklist         
* #2371  suggestion porn blacklist         
* #2351  suggestion porn blacklist         
* #2346  suggestion porn blacklist         
* #2342  suggestion porn blacklist         
* #2337  suggestion porn blacklist

**Closed** 2023-08-06 09:50 UTC
