### ISSUE TITLE
The big hosts file seems to cause a significant slowdown on Windows7 SP1

### ISSUE THREAD

**Issue by krasi0** [StevenBlack/hosts#93] opened 2016-02-23 10:22 UTC
This is mostly noticeable once a network interface becomes enabled. Ping commands and establishing new connections don't appear to work during the first 40-50 seconds or so

**Comment by Laicure** [comment] 2016-02-23 13:24
Hi @krasi0, can you provide the sources that you have used? Everything seems fine on my phone and system using the default sources from this repo though I have delays too but just less than a minute. And what kind of _new_ connections are those?

**Comment by krasi0** [comment] 2016-02-23 13:53
Hey, @Laicure ! I have been using the file downloaded straight from https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

I am describing an issue where svchost.exe uses 100% CPU for about 20 seconds or more (parsing the big hosts file I presume) once I enable an ethernet interface (I have to disable / enable it quite frequently for ... reasons). During that delay nothing resolves or no outbound tcp/ip connections are possible. Afterwards, the delays are no longer that big. 

My question: would you happen to know if there is a way to somehow cache the parsed hosts file between dis/enabling the ethernet interface, so that I avoid that initial delay I am describing?

Thanks in advance!

**Comment by Laicure** [comment] 2016-02-23 20:25
/hmm
Is your **DNS Client** running?
~~I think it should not reparse the hosts file whenever there are connect/disconnect scenarios~~ (except on my Windows Phone though, it takes at least 30 sec to establish a connection).

Have you tried _not_ using the hosts file and rerun the disable/enable interface thing and see the differences?

I am using a modified hosts file from this repo, (forked it, UI revamp for Windows users but still follows the concepts of this repo). Maybe you can [try it](https://raw.githubusercontent.com/Laicure/HostsX/master/hosts).

**Comment by krasi0** [comment] 2016-02-23 20:29
Yes, the DNS client is running. With the default, small hosts file there
isn't such a big delay. I will have a look at your hosts file.

Thanks!

On Tue, Feb 23, 2016 at 10:25 PM, Laicurè Leviarè <notifications@github.com>
wrote:

> /hmm
> Is your *DNS Client* running?
> I think it should not reparse the hosts file whenever there are
> connect/disconnect scenarios (except on my Windows Phone though, it takes
> at least 30 sec to establish a connection).
>
> Have you tried *not* using the hosts file and rerun the disable/enable
> interface thing and see the differences?
>
> I am using a modified hosts file from this repo, (forked it, UI revamp for
> Windows users but still follows the concepts of this repo). Maybe you can try
> it <https://raw.githubusercontent.com/Laicure/HostsX/master/hosts>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StevenBlack/hosts/issues/93#issuecomment-187887914>.
>



-- 
BR

**Comment by krasi0** [comment] 2016-02-23 20:36
I experience the same issues with your curated hosts file. I guess, it's
the close to 1MB size that causes svchost.exe to take a while... Sigh

On Tue, Feb 23, 2016 at 10:28 PM, Krasimir Krastev <krasi000@gmail.com>
wrote:

> Yes, the DNS client is running. With the default, small hosts file there
> isn't such a big delay. I will have a look at your hosts file.
>
> Thanks!
>
> On Tue, Feb 23, 2016 at 10:25 PM, Laicurè Leviarè <
> notifications@github.com> wrote:
>
>> /hmm
>> Is your *DNS Client* running?
>> I think it should not reparse the hosts file whenever there are
>> connect/disconnect scenarios (except on my Windows Phone though, it
>> takes at least 30 sec to establish a connection).
>>
>> Have you tried *not* using the hosts file and rerun the disable/enable
>> interface thing and see the differences?
>>
>> I am using a modified hosts file from this repo, (forked it, UI revamp
>> for Windows users but still follows the concepts of this repo). Maybe you
>> can try it
>> <https://raw.githubusercontent.com/Laicure/HostsX/master/hosts>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/StevenBlack/hosts/issues/93#issuecomment-187887914>.
>>
>
>
>
> --
> BR
>



-- 
BR

**Comment by StevenBlack** [comment] 2016-02-23 21:10
There should be no delay at all.  Like, imperceptible.

Closing because this is a local machine config/firewall/AV thing.  It's Windows.

**Closed by StevenBlack** 2016-02-23 21:10 UTC

**Comment by FadeMind** [comment] 2016-02-24 07:59
@StevenBlack This is issue in DNS cache setup. Hard workaround:
![screenshot_20160224_085830](https://cloud.githubusercontent.com/assets/9846948/13278995/ccc7156a-dad4-11e5-8c71-6c72b8ba2ccd.png)

SRC: http://winhelp2002.mvps.org/hostswin7.htm

Windows 10 have fixed this issue and don't need any regfix.

**Comment by linuxandria** [comment] 2020-03-02 17:07
I've noticed if you go above 10k hosts in win10 dns is unusable, like all reqeuests time out

**Comment by mondjunge** [comment] 2020-05-20 07:57
I can confirm this is happening again since one of the last Windows 10 updates. It took some time to find out why the wifi is taking up to 3 minutes to connect to the internet. The PC is running fine for years. Haven't updated the hosts in quite some time.

This seems to be a  windows DNS Client Bug regression from Win 7 days. I can see my DNS-Client consumes a full Thread at 100% until internet connectivity is established.

Connection is instant when I put the original hosts file in place.

I just leave my two cents here for other wanderers.

**Comment by funilrys** [comment] 2020-05-20 08:02
As usual while commenting about Windows behavior: I rarely use Windows personally.

But, disabling the DNS client might help? 🤔
