### ISSUE TITLE
Website inc.com is blocked

### ISSUE THREAD

**Issue by lencc** [StevenBlack/hosts#61] opened 2016-01-22 19:41 UTC
The content on inc.com doesn't load. I suspect hosts file, because I also tested it with disabled adblocker and Firefox Tracking protection which doesn't help.

The problem is that I manually removed the entry <code>inc.com</code> from my hosts file and website still doesn't load.

**Comment by Laicure** [comment] 2016-01-22 19:50
Saw the **0.0.0.0 inc.com** entry in the hosts file. Have you tried clearing up the browser cache?

**Comment by lencc** [comment] 2016-01-22 20:14
Yes, I also cleaned all the history (including flash cookies) and restarted the browser, but unfortunatelly it doesn't help.

**Comment by StevenBlack** [comment] 2016-01-22 21:53
inc.com is [blocked by yoyo](https://github.com/StevenBlack/hosts/blob/ded40d2fb2b48ee21623271e5272cde104ed5702/data/yoyo.org/hosts#L1589) at line 1589.

**Comment by lencc** [comment] 2016-01-22 22:51
It must be some additional entry blocking content on the website. When opened, only top navigation bar appears, [as shown here](http://i.imgur.com/JZwCn1O.png).

**Comment by StevenBlack** [comment] 2016-01-23 17:02
Closing this, not a bug here.

**Closed by StevenBlack** 2016-01-23 17:02 UTC
