### ISSUE TITLE
Service Host: DNS Client uses > 50% CPU and block for min 5min the net

### ISSUE THREAD

**Issue by AngelTs** [StevenBlack/hosts#757] opened 2018-08-15 14:10 UTC
From a few months from now, host file under Win10 Pro 64bit 1803 17134.191 is the reason "DNS Client" (svchost.exe) to use 50-55% of CPU each time when the internet is activated. Also to block the internet for at least 5min during this process!
Obvious, it is bug of DNS Client, but this bug is not exist in early versions of host file (2017>).
So I am wonder, is it possible some host name(s) in host file to rise this bug?
Anybody to feel the same f..g problem?

**Comment by funilrys** [comment] 2018-08-15 14:14
Duplicate of #710  ?

**Comment by AngelTs** [comment] 2018-08-15 14:28
in #710 they discuss the host file size. I don't think this is the real problem, because just few months ago everything works fine with almost the same file host size- the real problem is in some strings as host names or ip addresses

**Comment by AngelTs** [comment] 2018-08-19 05:55
@ScriptTiger Thank you so much for your perfect resolution. This is the right one- I just put "-c" in "python updateHostsFile.py …" and everything works like a charm, without delay or high CPU usage.
Thank you again for your perfect work.

**Closed** 2018-08-19 05:55 UTC

**Comment by ScriptTiger** [comment] 2018-08-19 06:13
@StevenBlack, I'm not sure if adding the `-c` switch to the updateHostsWindows.bat or just adding a bold/highlighted note to Windows users would be best, but addressing this would definitely solve most issues Windows users have. It can even cause seemingly unrelated networking issues by jamming up networking services and many people don't think to try this.
