### ISSUE TITLE
Non GitHub mirror sbc.io Error 404 Not Found

### ISSUE THREAD

**Issue by mikhaelkh** [StevenBlack/hosts#1549] opened 2021-02-17 00:39 UTC
'404 Not Found' response for http://sbc.io/hosts/hosts or other hosts variants.

**Comment by dnmTX** [comment] 2021-02-17 03:21
@mikhaelkh use this link temporarily until the problem is fixed: https://www.celsoazevedo.com/hosts/ 

ping Steven @StevenBlack

**Comment by StevenBlack** [comment] 2021-02-17 04:25
Hi Michael @mikhaelkh thank you for this.

Fixed!

Closing.

**Closed by StevenBlack** 2021-02-17 04:25 UTC
