### ISSUE TITLE
myhosts file cannot contain special characters

### ISSUE THREAD

**Issue by mikecurtin** [StevenBlack/hosts#158] opened 2016-08-08 19:24 UTC
I am having an issue with merging "myhosts". If "myhosts" contains a character such as `Ö` or `é` , even when commented out, the final "hosts" file will be output incorrectly. ("hosts" file will be truncated and not hold any other changes that are located in "myhosts".

**Comment by Atavic** [comment] 2016-09-13 22:01
That's by design: http://www.w3schools.com/tags/ref_urlencode.asp

An URL request containing **ö** to work correctly will encode it as **%C3%B6**

**Comment by StevenBlack** [comment] 2016-09-16 22:26
@FadeMind what do you think?  Close this?

**Comment by FadeMind** [comment] 2016-09-17 06:45
@StevenBlack 

@Atavic explained issue. IMO **invalid** label = **not a bug** = **closed**

**Closed** 2016-09-17 13:04 UTC
Labels: discussion
