### ISSUE TITLE
Error Updating KADHosts (Windows 10 / Python 2.7)

### ISSUE THREAD

**Issue by knarf1** [StevenBlack/hosts#382] opened 2017-08-12 21:37 UTC
Running the Windows Batch Update file, I get an error updating KADHosts that says the file can not be updated.  The resulting hosts file in that folder is 0 bytes.

If I copy the "Raw" data from that list (copy / paste from github raw) into my Blacklist, I get another (Python) error indicating that there are characters which cannot be processed and then the blacklist does not get processed.

If I then delete the "Commented" out KADhosts section description lines from my Blacklist, it adds the sites from my blacklist just fine and the script finishes.

I'm guessing there is some character conversion that needs to happen in Python in order to write to Windows files that is going awry, but I'm not sure.

Hope this helps.

**Comment by rautamiekka** [comment] 2017-08-12 22:08
The outputs/logs please. Otherwise this is useless.

**Comment by knarf1** [comment] 2017-08-12 22:33
As I said, the output from KAD is a 0 byte file.

Not sure where I'd get a log. Checked TEMP folder around time of last run, but found nothing.

Sorry it's useless.   I have a (clunky) work-around. I guess people should use that until someone with more knowledge than I have also has the problem and reports it.

**Comment by rautamiekka** [comment] 2017-08-12 22:37
^ You say `Running the Windows Batch Update file, I get an error updating [...]`, that's the output, and any other output given that makes you think something off. The hosts file ain't an output.

**Comment by knarf1** [comment] 2017-08-12 22:42
OK.  I assumed "the output" what what the script output.

The error generated by the script isn't very useful, but here it is verbatim:

"Error in updating source:  https://raw.githubusercontent.com/azet12/KADhosts/master/KADhosts.txt"

Then KADHosts.txt has 0 bytes.

Hope this helps in troubleshooting.

**Comment by rautamiekka** [comment] 2017-08-12 22:46
^ That's **everything** the script said ?

**Comment by knarf1** [comment] 2017-08-12 22:49
When I ran the script as it is, yes.  That's everything out of the ordinary that the script said.

When I manually put KADHosts.txt into blacklist unedited I got this:
```
Traceback (most recent call last):
  File "d:\hosts\updateHostsFile.py", line 1230, in <module>
    main()
  File "d:\hosts\updateHostsFile.py", line 163, in main
    merge_file = create_initial_file()
  File "d:\hosts\updateHostsFile.py", line 552, in create_initial_file
    write_data(merge_file, curFile.read())
  File "d:\hosts\updateHostsFile.py", line 982, in write_data
    f.write(str(data).encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 199: ordinal not in range(128)
```
Like I said, if someone just runs the script as it is, the only indication of a problem they'll get is:
"Error in updating source: https://raw.githubusercontent.com/azet12/KADhosts/master/KADhosts.txt"

and a 0 byte file in that folder.

**Comment by StevenBlack** [comment] 2017-08-12 23:28
This is a duplicate of #372.

**Comment by funilrys** [comment] 2018-03-03 20:20
Not sure about this one but it should also be fixed @StevenBlack :+1:

**Comment by StevenBlack** [comment] 2018-03-03 20:21
Yup, toast on the coast.

**Closed by StevenBlack** 2018-03-03 20:21 UTC
