### ISSUE TITLE
lib.rus.ec

### ISSUE THREAD

**Issue by kravietz** [StevenBlack/hosts#1080] opened 2019-11-01 19:49 UTC
The whole domain `lib.rus.ec` is being blocked. This is domain of the Library Genesis project at http://gen.lib.rus.ec/ which aims at giving free access to scientific research. It is controversial as it violates copyright of large publishers, but otherwise does not publish malware etc so unless this blacklist aims at piracy prevention this one should be whitelisted.

**Comment by StevenBlack** [comment] 2019-11-01 22:49
Hi @kravietz thank you for this.

This domain comes to us via [CoinBlockerList](https://gitlab.com/ZeroDot1/CoinBlockerLists).  Can you please raise this issue at this location?  https://gitlab.com/ZeroDot1/CoinBlockerLists/issues

Ping @ZeroDot1, not sure if he monitors this repo since CoinBlocker is housed at GitLab.

**Comment by ZeroDot1** [comment] 2019-11-02 05:22
Hi @StevenBlack & @kravietz,
I checked the URL again, and since there is no mining code available I deleted the URL from the list.
The update for the [CoinBlockerLists](https://zerodot1.gitlab.io/CoinBlockerListsWeb/downloads.html) will be released next week.

**Comment by kravietz** [comment] 2019-11-02 07:01
Thank you @StevenBlack @ZeroDot1 that was quick!

**Comment by afonari** [comment] 2019-12-04 01:30
Blocked again, can this be re-opened?

**Comment by StevenBlack** [comment] 2019-12-04 01:32
@ZeroDot1 can you address this?  Thanks!

**Comment by llacb47** [comment] 2019-12-08 03:45
Hello @ZeroDot1...

**Comment by afonari** [comment] 2019-12-08 14:27
Here: https://gitlab.com/ZeroDot1/CoinBlockerLists/blob/master/hosts_browser#L826

**Comment by StevenBlack** [comment] 2019-12-08 17:44
Alexander @afonari and Pawel @kravietz, I just [opened a specific issue for this](https://gitlab.com/ZeroDot1/CoinBlockerLists/issues/55).  I'm hoping for resolution, very soon.

**Comment by ZeroDot1** [comment] 2019-12-10 20:11
OK, I can publish a small update tomorrow to solve the problem.

**Comment by StevenBlack** [comment] 2019-12-10 20:19
@ZeroDot1 yes well we've heard that assurance before.

**Comment by StevenBlack** [comment] 2019-12-10 20:23
Alexandr @afonari Pawel @kravietz the problem is resolved in the [latest release](https://github.com/StevenBlack/hosts/releases/tag/2.5.29).

Closing.

**Closed by StevenBlack** 2019-12-10 20:23 UTC

**Comment by ZeroDot1** [comment] 2019-12-10 21:02
![Bildschirmfoto vom 2019-12-10 22-01-10](https://user-images.githubusercontent.com/28985171/70568687-49770980-1b90-11ea-9ddc-88943892b0cb.png)

**Comment by spirillen** [comment] 2019-12-17 09:18
Hi @StevenBlack I think you should re-open this issue as you reference to it in the https://gitlab.com/ZeroDot1/CoinBlockerLists/issues/55 as it's still unresolved... Just my 1 cent
