### ISSUE TITLE
cdn.jsdelivr.net is listed twice in same file

### ISSUE THREAD

**Issue by strotee** [StevenBlack/hosts#1753] opened 2021-08-31 19:59 UTC
I saw this [issue](https://github.com/StevenBlack/hosts/issues/1377) opened a year ago and it was instructed for the issue opener to contact mvps.  Today, in https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts, it's disabled on line #64539 (mvps) and then later re-enabled on line #100910. Disabling the latter line allows a site (https://uupdump.net) I regularly visit to display properly. Thanks

**Comment by dnmTX** [comment] 2021-09-02 17:15
@strotee the issue is fixed. See #1754. Just be patient until the list gets updated and you can also close this one 👍

**Comment by StevenBlack** [comment] 2021-09-02 17:20
Closing.

**Closed by StevenBlack** 2021-09-02 17:20 UTC
