### ISSUE TITLE
Samsung non-removable spyware

### ISSUE THREAD

**Issue by DavidCWGA** [StevenBlack/hosts#1117] opened 2020-01-07 03:10 UTC
Details: https://www.reddit.com/r/Android/comments/ektg8u/chinese_spyware_preinstalled_on_all_samsung/

List of hosts:

```
aicleaner.shouji.360.cn
care.help.360.cn
eul.s.360.cn
g.s.360.cn
mclean.cloud.360safe.com
mclean.f.360.cn
mclean.lato.cloud.360safe.com
mclean.uk.cloud.360safe.com
mvconf.cloud.360safe.com
mvconf.f.360.cn
mvconf.lato.cloud.360safe.com
mvconf.uk.cloud.360safe.com
p.s.360.cn
```

**Comment by StevenBlack** [comment] 2020-01-07 03:23
David @DavidCWGA thank you.  This is good!

**Comment by StevenBlack** [comment] 2020-01-07 05:04
Done!  Closing!

**Closed by StevenBlack** 2020-01-07 05:04 UTC

**Comment by XhmikosR** [comment] 2020-01-09 07:44
@StevenBlack are you sure about this addition? Won't this prevent the Device Cleaner from updating its definitions?

**Comment by StevenBlack** [comment] 2020-01-09 15:49
Hi @XhmikosR I can't evaluate what you are saying.  Maybe you Presume I know what "Device Cleaner" means?  I don't know what you mean when you say, "Device Cleaner".

**Comment by Laicure** [comment] 2020-01-09 15:52
Hi @StevenBlack, the *Device Cleaner* is the one installed on Samsung devices that connects through those listed domains.
It's a system app with lots of default permission requests and resides inside the Settings menu of the phones. (according to the reddit link above)

**Comment by XhmikosR** [comment] 2020-01-09 15:55
Don't get me wrong, I'm all for blocking stuff. I'm just trying to figure out if there's a definitive answer as to what those packets contain. Because blocking these domains will make the Device Cleaner not be able to update, right?

**Comment by StevenBlack** [comment] 2020-01-09 15:57
Thank you Laicurè @Laicure.

I suppose we'll need a Samsung device owner to check.

I'd also like to know, why would anyone need *Device Cleaner*?  In the MacOS space, and the Windows Space too (usually), that sort of thing is scam.

**Comment by XhmikosR** [comment] 2020-01-09 15:58
>I'd also like to know, why would anyone need Device Cleaner? In the MacOS space, and the Windows Space too (usually), that sort of thing is scam.

Well, that's not for us to decide :)

All I wanted to say is that unless someone analyzes the packets sent, we can't just assume it's bad. Although I'd rather err on the safe side, I don't think we should break this feature unless it's confirmed.

**Comment by StevenBlack** [comment] 2020-01-09 16:00
@XhmikosR I understand what you're saying.  I'm prone to agree, except I'm more prone to distrust .cn domains that appear unrelated to the corporations we're discussing.  Like Samsung, for example.

**Comment by AnonymousPoster** [comment] 2020-01-09 23:25
360 Total Security is AdWare, MalWare and SpyWare software disguised as anti-virus

Once it first installed it puts ads everywhere, collect a hole bunch of data about you etc. etc.

You can read a bit more at these links if you like
- http://wiki.mypdns.org/ticket/63
- https://github.com/mypdns/matrix/issues/3
