### ISSUE TITLE
DNS Client High Cpu Usage

### ISSUE THREAD

**Issue by norage** [StevenBlack/hosts#710] opened 2018-07-08 07:02 UTC
Hello!

I've seen people with similar issues with connectivity when using this huge hosts file. I just switched over to winhelp2002 mvps file from this one and for some reason, DNS Client didn't react to it. I no longer have these 10-30s delays when connecting to the net or switching on/off VPN. Could it be due to the file size? Hosts.mvps is (today) 465KB while "StevenBlacks" is 2038KB (depending on which one you choose).

**Comment by CHEF-KOCH** [comment] 2018-07-08 08:34
Windows HOSTS file was never designed to be an ad-blocking solution, so this is not only on your end or affects only a few people, that's quite normal. Svchost.exe is rising high cpu because the dns service tries to resolve all domains one by one which is ineffective.

The only thing you can do is install AdGuard or use Unbound or another DNS system which is more efficient when it comes to blacklisting domains.

See also #93

**Comment by funilrys** [comment] 2018-07-08 08:42
Also #411 #695

**Comment by funilrys** [comment] 2018-07-08 08:46
If we are talking about file size you can also see #459 (`--compress` ==> [cf.](https://github.com/StevenBlack/hosts#command-line-options))

**Comment by CHEF-KOCH** [comment] 2018-07-08 11:30
You can't disable DNSCache anymore that easy since Windows 10 RS 3 the DNSCache 'stop' function is gone via services.msc and even if you disable it via registry it might get reset after a restart/update or whenever a depending service starts it.

Again the HOSTS file (no matter which OS) and especially not on Windows is not designed to be an ad-blocker, you over the long term have to use AdGuard or hardware based Pi-Hole which is more efficient, especially because it also work with regular expressions, which reduces the hosts file up to 80% since you easily can work with wildcards like .* etc.

To compress the hosts is also not effective at some point, especially not with 100k+ entries.  You have to face the fact that HOSTS is a very very bad solution and causes more troubles rather than it helps, if you already distrust Windows own DNS mechanism just use dnscrypt and combine it with unbound, that doesn't cost much system resources and as a benefit you improve your security setup + can easier work with hosts, especially because you can automatically update the hosts file via unbound while you usually also need third-party tools here in order to do that.

There several guides here:
* https://etherarp.net/build-an-adblocking-dns-server/
* https://news.ycombinator.com/item?id=11084968
* https://github.com/lepiaf/adblock-unbound
* https://deadc0de.re/articles/unbound-blocking-ads.html

If you like to do this more professional with thousands of entries there is no way around a [Pi-Hole](https://pi-hole.net) (or a similar script). The benefit is obvious, optimized for DNS related ads-blocking, works on all network devices without any applications and you get a nice GUI in order to minor + white-/blacklist something.

**Comment by Laicure** [comment] 2018-07-08 15:02
Yes, that win10 thing is really pissing me off so I just stopped updating the hosts file at work.

(using win8.1pro at home, hosts file works well)

Off topic:
oh those are cool!

But on my case, as an average power-user.
I only have my laptop, android phones, and my not-so-customizable router-modem at home, I am not able to setup those kinds (you know, no server thingy).

Though I am really interested setting up one ('cause it's damn tedious setting up all the hosts file on each device, rooted and non-rooted), thanks for the links, unbound looks easy to setup ;)

**Comment by StevenBlack** [comment] 2018-07-08 19:03
Thank you, everyone, for the excellent community response to this issue.

Some really cool people are watching this repo.  I'm thankful for that!

I'd like to echo @CHEF-KOCH when he recommends [Pi-Hole](https://pi-hole.net/).  Pi-Hole is a great project and a great reason for everybody to get into Raspberry Pi devices more generally.

**Comment by StevenBlack** [comment] 2018-07-08 19:03
Closing!

**Closed by StevenBlack** 2018-07-08 19:03 UTC

**Comment by Al-Green-COS** [comment] 2021-01-03 20:18
This issue can be successfully resolved via regedit by removing 'DNSCache' entry from NetworkService REG_MULTI_SZ at:

1) HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Svchost

2) HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Svchost

Prior to this I had to wait ~10 minutes for SVCHOST DNS Client to complete its process when using Steven Black's hosts file. After making this change, I no longer have to wait. Enjoy....

**Comment by funilrys** [comment] 2021-01-06 17:15
If confirmed that one should definitely be in the README Steve @StevenBlack !

**Comment by StevenBlack** [comment] 2021-01-06 17:17
Al @Al-Green-COS what version of Windows is this?

**Comment by dnmTX** [comment] 2021-01-06 18:27
@Al-Green-COS isn't it that the same as to disable the **DNS Client** in Services? Not sure why the extra steps,especially when it comes to messing with registry entries?
![Capture](https://user-images.githubusercontent.com/34774426/103805957-ecab8400-5019-11eb-8484-417ad8738ee9.PNG)

> Al @Al-Green-COS what version of Windows is this?

Steve @StevenBlack it doesn't matter. I'm with 1607 and i do have the option to do it and i'm pretty sure @Al-Green-COS is on a much higher version then me.
![Help](https://user-images.githubusercontent.com/34774426/103806334-79564200-501a-11eb-9e01-e20582c7b2d4.png)

**Comment by Al-Green-COS** [comment] 2021-01-06 19:50
dnmTX,

In the latest releases of Windows 10 it’s no longer possible to disable DNS Client via Services. I don’t know what release it was that you could no longer do this. I’m presently on Windows 10 Release 20H2 (2009).

[cid:image003.png@01D6E42A.8CBC5340]

As you can see, the buttons for Start, Stop, Pause, and Resume are grayed out.

If you’re able to do this, please advise as to the Windows 10 release you are on.

  *   reg query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /v ReleaseID

Respectfully,

Al Green

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dnmTX** [comment] 2021-01-06 23:09
@Al-Green-COS  i see. I didn't know that but it's less then suprising for me to be honest.
Still,another less coplicated option would be to go to:
`HKLM\SYSTEM\CurrentControlSet\Services\Dnscache` and change `Start` from 2 to 4(disabled) and Restart
Can you confirm if this option is still possible on the build that you're on. Thank you 👍

**Comment by Al-Green-COS** [comment] 2021-01-06 23:32
Mr. Black,

[cid:image003.png@01D6E449.8CD8C3D0]

Respectfully,

Al Green

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Al-Green-COS** [comment] 2021-01-07 00:00
dnmTX,

Your recommendation works as well.
[cid:image002.png@01D6E44D.5C7A6C30]


[cid:image004.png@01D6E44D.0FDBB500]

Respectfully,

Al Green
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by robpomeroy** [comment] 2021-03-25 09:35
A note for the unwary: I applied the changes recommended in this thread, rebooted and it broke file share browsing. I could no longer access files on my NAS (a Synology). Reverting the changes restored access (after another reboot).

The underlying cause of high CPU in my case was a faulty USB hub with a built-in network adapter. It was constantly connecting and disconnecting as evidenced by entries in event logs. This may have been specific to Hyper-V, which automatically reprovisions network devices on discovery.

**Comment by lmstearn** [comment] 2023-03-16 15:20
[High usage](https://superuser.com/questions/1318155/large-hosts-file-causing-high-dns-client-cpu-usage) on W10 startup while DNS Client processes all the urls in the hosts file. Presumably it calls [add-dnsserverresourcerecord](https://learn.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecord?view=windowsserver2022-ps) to the cache for use with Store/ActiveDirectory or some other non-browser based operations. If, for some reason Windows shutdown is not successful, the DNS cache gets flushed on reboot, so the db has to be rebuilt.
