### ISSUE TITLE
Raven.js

### ISSUE THREAD

**Issue by Technetium1** [StevenBlack/hosts#785] opened 2018-09-20 02:18 UTC
https://github.com/StevenBlack/hosts/blob/1e9311b9353ba95c34a05f297ac4fb3ca8b8be40/data/lightswitch05/hosts#L5241

Raven.js is not malicious and `cdn.ravenjs.com` should not be on this list

**Comment by funilrys** [comment] 2018-09-20 08:03
Hi @Technetium1,
and welcome here!

I'm sure that @lightswitch05 will let you know about this.

Have a nice day/night.

**Comment by dnmTX** [comment] 2018-09-20 09:50
Trackers and telemetry are not malicious either that doesn't mean they don't belong here.Looking at the domain in question looks like one of those.

**Comment by lightswitch05** [comment] 2018-09-20 10:28
Also, duplicate this ticket is a duplicate of https://github.com/StevenBlack/hosts/issues/705

**Comment by StevenBlack** [comment] 2018-09-20 13:57
Thanks everybody!

Closing.

**Closed by StevenBlack** 2018-09-20 13:57 UTC
