### ISSUE TITLE
HTTPS for HOSTS files

### ISSUE THREAD

**Issue by QGkjTIYUCw** [StevenBlack/hosts#731] opened 2018-07-27 09:56 UTC
Hello.

It seems that your **HOSTS** files on the **Non Github mirror** can only be retrieved via the **HTTP** protocol.
Please make it possible to receive these **HOSTS** files using the **HTTPS** protocol also. This is very important for safety. An attacker can replace a **HOSTS** file, in which there will be a redirection of banking websites, e-mail websites, other websites to phishing websites.

Thank you.

**Comment by kronflux** [comment] 2018-07-27 17:39
Just to simplify the ticket, he's asking to please enable HTTPS on the web server hosting "sbc.io", as an attacker could potentially hijack the HTTP connection and replace the hosts list being provided by the mirror with a malicious version.

**Comment by lightswitch05** [comment] 2018-07-27 17:41
@oqbnaslyxt if you can't use the Github links which are HTTPS, you might want to try jsDelivr. Its a CDN that you can use for any content hosted on Github. I've updated the chart below to use jsDelivr links instead. I have no idea if this website works with Hostsman. Although this is HTTPS, it leads to another question to trust. This is content going through a 3rd party, where "sbc.io" is Steven's own website.

Host file recipe | Readme | Raw hosts | Unique domains | Non Github mirror
---------------- |:------:|:---------:|:--------------:|:-------------:
Unified hosts = **(adware + malware)** | [Readme](https://github.com/StevenBlack/hosts/blob/master/readme.md) | [link](https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts) | 60,564 | [link](https://cdn.jsdelivr.net/gh/StevenBlack/hosts/hosts)
Unified hosts **+ fakenews** | [Readme](https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews/readme.md) | [link](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts) | 61,233 | [link](https://cdn.jsdelivr.net/gh/StevenBlack/hosts/alternates/fakenews/hosts)
Unified hosts **+ gambling** | [Readme](https://github.com/StevenBlack/hosts/blob/master/alternates/gambling/readme.md) | [link](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling/hosts) | 62,182 | [link](https://cdn.jsdelivr.net/gh/StevenBlack/hosts/alternates/gambling/hosts)
Unified hosts **+ porn** | [Readme](https://github.com/StevenBlack/hosts/blob/master/alternates/porn/readme.md) | [link](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts) | 70,642 | [link](https://cdn.jsdelivr.net/gh/StevenBlack/hosts/alternates/porn/hosts)
Unified hosts **+ social** | [Readme](https://github.com/StevenBlack/hosts/blob/master/alternates/social/readme.md) | [link](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/social/hosts) | 61,722 | [link](https://cdn.jsdelivr.net/gh/StevenBlack/hosts/alternates/social/hosts)
Unified hosts **+ fakenews + gambling** | [Readme](https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews-gambling/readme.md) | [link](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts) | 62,851 | [link](https://cdn.jsdelivr.net/gh/StevenBlack/hosts/alternates/fakenews-gambling/hosts)
Unified hosts **+ fakenews + porn** | [Readme](https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews-porn/readme.md) | [link](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-porn/hosts) | 71,311 | [link](https://cdn.jsdelivr.net/gh/StevenBlack/hosts/alternates/fakenews-porn/hosts)
Unified hosts **+ fakenews + social** | [Readme](https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews-social/readme.md) | [link](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-social/hosts) | 62,391 | [link](https://cdn.jsdelivr.net/gh/StevenBlack/hosts/alternates/fakenews-social/hosts)
Unified hosts **+ gambling + porn** | [Readme](https://github.com/StevenBlack/hosts/blob/master/alternates/gambling-porn/readme.md) | [link](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-porn/hosts) | 72,260 | [link](https://cdn.jsdelivr.net/gh/StevenBlack/hosts/alternates/gambling-porn/hosts)
Unified hosts **+ gambling + social** | [Readme](https://github.com/StevenBlack/hosts/blob/master/alternates/gambling-social/readme.md) | [link](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-social/hosts) | 63,340 | [link](https://cdn.jsdelivr.net/gh/StevenBlack/hosts/alternates/gambling-social/hosts)
Unified hosts **+ porn + social** | [Readme](https://github.com/StevenBlack/hosts/blob/master/alternates/porn-social/readme.md) | [link](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn-social/hosts) | 71,799 | [link](https://cdn.jsdelivr.net/gh/StevenBlack/hosts/alternates/porn-social/hosts)
Unified hosts **+ fakenews + gambling + porn** | [Readme](https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews-gambling-porn/readme.md) | [link](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts) | 72,929 | [link](https://cdn.jsdelivr.net/gh/StevenBlack/hosts/alternates/fakenews-gambling-porn/hosts)
Unified hosts **+ fakenews + gambling + social** | [Readme](https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews-gambling-social/readme.md) | [link](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-social/hosts) | 64,009 | [link](https://cdn.jsdelivr.net/gh/StevenBlack/hosts/alternates/fakenews-gambling-social/hosts)
Unified hosts **+ fakenews + porn + social** | [Readme](https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews-porn-social/readme.md) | [link](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-porn-social/hosts) | 72,468 | [link](https://cdn.jsdelivr.net/gh/StevenBlack/hosts/alternates/fakenews-porn-social/hosts)
Unified hosts **+ gambling + porn + social** | [Readme](https://github.com/StevenBlack/hosts/blob/master/alternates/gambling-porn-social/readme.md) | [link](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-porn-social/hosts) | 73,417 | [link](https://cdn.jsdelivr.net/gh/StevenBlack/hosts/alternates/gambling-porn-social/hosts)
Unified hosts **+ fakenews + gambling + porn + social** | [Readme](https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews-gambling-porn-social/readme.md) | [link](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts) | 74,086 | [link](https://cdn.jsdelivr.net/gh/StevenBlack/hosts/alternates/fakenews-gambling-porn-social/hosts)

**Comment by kronflux** [comment] 2018-07-27 18:07
Let's be honest, it's about time @StevenBlack gets with the HTTPS age anyway 😂 Chrome is going to start automatically blocking non HTTPS queries soon by default!

**Comment by oqbnaslyxt** [comment] 2018-07-27 19:12
**HostsMan** does not currently support **HTTPS**. I already wrote about this in their support. I hope that they will soon fix it.

In the meantime, I work around this problem with the **wget.exe** utility. It periodically downloads **HOSTS** files over **HTTPS** to a local disk, and **HostsMan** takes these files from the local disk.

**Comment by ScriptTiger** [comment] 2018-09-25 17:43
The "github.io" can serve HTTPS files without a problem since it was designed specifically to be the front-end Web service for user Web content. It doesn't have the issues that files served from "raw.githubusercontent.com" have, as that domain does not specialize specifically in serving Web content and has certain restrictions and limitations in place.

That being said, we have talked about the implementation of GitHub pages for this repo in the past and @StevenBlack has shown positive interest in implementing something in the future, but understandably setting up yet another website for the statically served GitHub pages is not an immediate priority given all the other options out there at the moment and the time it takes for website design considerations, etc., etc.

If you really want to download the hosts files directly from GitHub over HTTPS, you can download any of the files hosted on my GitHub pages:

For the standard hosts file format:
https://scripttiger.github.io/hosts-packages/

For various other formats for use with server blacklists, gateway routers, etc.:
https://scripttiger.github.io/alts/

**Comment by StevenBlack** [comment] 2020-02-24 03:17
We will do this... Please disregard Stale Bot.

**Comment by XhmikosR** [comment] 2020-04-11 06:43
@StevenBlack I believe this is sort of a duplicate of #878?

**Closed** 2020-04-11 13:26 UTC
Labels: enhancement
