### ISSUE TITLE
with Python3, required lxml 4.1.1 doesn't build on Win10 but lxml 4.2.4 installs fine

### ISSUE THREAD

**Issue by dc55028** [StevenBlack/hosts#765] opened 2018-08-27 13:36 UTC
Running on Windows10 with Python 3, while installing the dependencies, lxml v4.1.1 doesn't build, but lxml v4.2.4 builds fine and the updateHostsWindows.bat works fine.

can you update the requirements.txt ?

**Comment by funilrys** [comment] 2018-08-27 13:47
Hi @dc55028 and welcome here!

Unfortunately, this is a duplicate of #751.

Cheers,
Nissar

**Comment by StevenBlack** [comment] 2018-08-27 16:32
Hi Dom @dc55028, see the readme for this repo.  You may need to...

    pip3 install --user -r requirements.txt

**Comment by funilrys** [comment] 2018-08-27 16:52
Or you get https://raw.githubusercontent.com/StevenBlack/hosts/python3only/requirements.txt (from the `python3only` branch which is not merge-able yet)  and do :

```
pip3 install --user -r path_to_the_downloaded_requirements.txt
```

**Closed** 2018-09-06 14:20 UTC
