### ISSUE TITLE
The Pirate Bay blocked

### ISSUE THREAD

**Issue by Elijahg** [StevenBlack/hosts#714] opened 2018-07-12 23:15 UTC
Seems that The Pirate Bay has ended up on your list, through the [CoinBlockerLists](https://gitlab.com/ZeroDot1/CoinBlockerLists). The maintainer of the CoinBlockerLists has [refused to remove](https://gitlab.com/ZeroDot1/CoinBlockerLists/issues/10) The Pirate Bay from the list; therefore I would recommend no longer using their lists for anti-censorship reasons. 

Thanks for the awesome lists!

**Comment by holdit** [comment] 2018-07-13 00:18
Yep, they're not just blocking hosts serving mining scripts, but also the websites using mining.

**Comment by funilrys** [comment] 2018-07-13 15:03
Duplicate of #713.

**Comment by StevenBlack** [comment] 2018-07-13 15:14
Yep, this is a duplicate.  Closing.

**Closed by StevenBlack** 2018-07-13 15:14 UTC

**Comment by Elijahg** [comment] 2018-07-13 15:15
Oops sorry, searched but nothing came up. Probably misspelt TBP!!
